### ISSUE TITLE
Crash when adding a newly made room.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#44] opened 2014-08-07 07:12 UTC
I've got this crash when placing a treasury tile after commit: 5f0e685bb85c4915a566febd409bff0ae6c5cd8c

(Note that the room tiles weren't shown anymore as reported in issue #39)

```
An internal Ogre3D error ocurred: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_13_12_9_node' not found. in SceneManager::getSceneNode at /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 920)
Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_13_12_9_node' not found. in SceneManager::getSceneNode at /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 920)
*** ERROR: Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_13_12_9_node' not found. in SceneManager::getSceneNode at /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 920)
```

TODO: Add back-trace or even better fix it

**Comment by Bertram25** [comment] 2014-08-07 07:13
@hwoarangmy For info. As I'm solely concerned so far, I'll try to get more info.

**Comment by hwoarangmy** [comment] 2014-08-07 08:13
Could you tell me more ? Which map have you tried ? How big was the new room ? Was it next to another treasury ? I will do some tests to see if I can reproduce.

**Comment by Bertram25** [comment] 2014-08-07 08:19
Sure. :)

> Which map have you tried ?

I tested it on TestSingleplayerSmall.level and TestSingleplayer.level

> How big was the new room ?

I tested adding one and several tiles.

> Was it next to another treasury ?

Now you tell it, yes it was, each time. I'll try later to add some unconnected rooms.

**Comment by hwoarangmy** [comment] 2014-08-07 09:23
I have tested both and I cannot reproduce the problem. Is it systematic ?

EDIT : tested under windows

**Comment by Bertram25** [comment] 2014-08-07 09:46
> Is it systematic ?

Fortunately, or unfortunately, yes it is under Linux. I'll check the logs, too, as Ogre might tell something.
Sorry for being troubles this time. ;)

**Comment by akien-mga** [comment] 2014-08-07 10:01
I'd definitely say "fortunately". A systematic bug is way better than an unpredictable one ;-)

**Comment by hwoarangmy** [comment] 2014-08-07 10:07
I will say the same. A systematic bug is usually not very difficult to debug. Even if sometimes, we just find that the architecture of the software is just not adapted and we have to break everything :)

**Comment by Bertram25** [comment] 2014-08-07 14:48
Yep. :) Still, I need to find some clues... Maybe this evening, but I can't tell, sorry.

**Comment by Bertram25** [comment] 2014-08-07 17:07
Latest news: 
When adding a room not connecting to a former one, the new room tile doesn't show up but no crash.

I tried disabling the RT shader init, but it doesn't change anything. Same behaviour.

**Comment by akien-mga** [comment] 2014-08-07 18:14
I experienced a crash when trying to place a "Treasure Room" tile next to the existing treasure room (spawn point) in TestSingleplayer.level. This was on Mageia 64bit with Nvidia GPU and proprietary driver:

```
An internal Ogre3D error ocurred: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_18_195_206_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_18_195_206_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
*** ERROR: Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_18_195_206_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
```

**Comment by akien-mga** [comment] 2014-08-07 18:20
Same thing with my Intel GPU with the open source intel driver:

```
Error prior to using GLSL Program Object : invalid value
Error prior to using GLSL Program Object : invalid value
An internal Ogre3D error ocurred: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_15_193_205_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_15_193_205_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
*** ERROR: Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_15_193_205_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
```

Note that the GLSL error from issue #41 appears with the intel GPU but not with nvidia.

**Comment by Bertram25** [comment] 2014-08-07 21:27
Hi there,
I'm sure the bug isn't related to the RT Shader as it is the same behaviour when not used, the game being uglier and the GLSL warnings removed are the only differences.

@akien-mageia I do think intel drivers have got a problem with certain glsl shaders. just as seen in this link (and many others):
https://www.opengl.org/discussion_boards/showthread.php/184437-GLSL-Shaders-not-working-on-Intel-drivers

The intel guys are surely working on improving all that. Yet, in the meanwhile, the shaders won't work very well, i guess.
In any way, I do think we can ignore the GLSL warning for now.

The next step will be to locate where the Treasury nodes are created and where in the code Ogre triggers an exception. We might find some clues there.

**Comment by Bertram25** [comment] 2014-08-07 21:46
@hwoarangmy Now we have two game maps, might there be that the unique room number used to create rooms doesn't work for any alignment reasons, different between windows and linux?

i explain:

I'm almost sure the exception is triggered here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/RenderManager.cpp#L425

Where the node is requested.

The name is build here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L563

The fact is: Are we sure you're speaking about the correct game map instance when building the name or requesting the node? Because if not, this would explain why the node: `Treasury_15_193_205_node` isn't found, as the client game map is expecting `Treasury_16_193_205_node` for instance, or whatever other unique number.
This would also explain why room tiles don't get refreshed. It is still some wild guess but it might trigger an idea. So, I'm firing it away. ;)

What do you think?

**Comment by hwoarangmy** [comment] 2014-08-08 09:47
As you can guess, I've add to deal with this kind of problem. So in fact, there are 2 phases :
- During map loading, both the client and the server build the gamemap using their own unique numbers which are expected to be equal (as they do everything on the same order, it should be).
- During game time, every game entity is created by the server only. It is it's responsability to give the name he chose to the clients to make sure every client has the same name.

Concerning tiles, they are all built during loading (phase 1) and only used during phase 2 (as tiles are not expected to be created at this stage). In the code, you can find some tile creation related code but I just kept it because it was already there. It is not called.

Concerning the rooms, I've just seen in the code that the second rule is not respected. It uses it's own unique number to create them. I will work on this to allow to force the room name. But in fact, I've removed all the static number. Now, they are all variables from the gamemap. So it should not be the reason why the room have not the same names. Even in a multiplayer game with many clients, building rooms at the same time, because of the message queues, the room will be built in the same order and the names should be the same.

As you already said, I would also guess that this exception and the fact that the rooms are not shown are related. I think we should focus on why they are not shown and, when it will be fixed, see if the exception still occurs.

If you want to have a look on why they are not shown, here is how it is supposed to work :
- The client sends a ClientNotification to ask to build room https://github.com/OpenDungeons/OpenDungeons/blob/development/source/GameMode.cpp#L504
- The server receives this message, sees if the room creation is allowed (checks the real tiles concerned, the money needed). If it is OK, the room is built on the server gamemap https://github.com/OpenDungeons/OpenDungeons/blob/development/source/ODServer.cpp#L636
- The room creation on the server gamemap triggers a message for the client saying that a new room has been built https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L172
- When the clients receive the buildRoom message, they build it https://github.com/OpenDungeons/OpenDungeons/blob/development/source/ODClient.cpp#L446

Concerning the room rendering, it is done in https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L206
As every rendering operation, there is a return for the server gamemap to ensure it doesn't do any rendering operation (which would result on an ogre exception saying that the mesh already exists).

Maybe you could add some logs at this places to ensure the room name in the sserver gamemap and in the client one are the same ?

BTW, could you tell me which desktop do you use (KDE, GNOME ?). I will try to download a mageia distrib as close as yours to see if I can reproduce the problem.

**Comment by akien-mga** [comment] 2014-08-08 10:01
> BTW, could you tell me which desktop do you use (KDE, GNOME ?). I will try to download a mageia distrib as close as yours to see if I can reproduce the problem.

I'm running KDE4 on Mageia Cauldron 64bit. Cauldron is the development version for the next stable release, and it's the only version which has all needed dependencies to build OD out of the box (namely OGRE 1.9.0 and CEGUI 0.8.3).

You can install it either through netinstall or using an ISO of Mageia5 alpha1 release last month: http://www.mageia.org/en/5/
Cauldron is by nature a rolling release, so expect daily updates since new releases of packages are pushed regularly: http://pkgsubmit.mageia.org/

**Comment by Bertram25** [comment] 2014-08-08 10:21
Hi @hwoarangmy Thanks for all the insight. I must say I was tracking the same paths when i received your comment. :)

> But in fact, I've removed all the static number. Now, they are all variables from the gamemap.

Good. :)

> Concerning the rooms, I've just seen in the code that the second rule is not respected. It uses it's own unique number to create them. I will work on this to allow to force the room name.

It's a good thing, but it might be a little more complicated than that:
There is an interesting comment here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L165

I think we have indeed two separate use cases to check. The room build and the room absorption by another one, recreating a third room. All that must trigger new tile names each time, right?

Maybe let's first check how an unconnected room name is made and fix it first. The absorbed ones will come shortly afterwards. (This is what you're proposing now I reread your comment. XD)
To simplify, maybe the server should tell the client to remove a room and add the new one (the third in my example), removing the absorption logic from the client side?

> Maybe you could add some logs at this places to ensure the room name in the sserver gamemap and in the client one are the same ?

Yep, I will and I'll report here what I can find.

Best regards,

**Comment by Bertram25** [comment] 2014-08-08 10:33
Ah, I was thinking we could also change some API to make sure of a few things:
- Rename the ODFrameListener game map to mClientGameMap & relatives, i.e.: getClientGameMap();
  and do the corresponding in the ODServer?

**Comment by hwoarangmy** [comment] 2014-08-08 11:22
@akien-mageia Thanks, I will download it and try.

@Bertram25 yes, that's my comment ;)
In fact, I had some trouble with room absorbtion. I had 2 choices :
- send the deletion message on the absorbed room and recreate everything.
- as the client already have all the information about the old room, ask him to build the new one and merge it himself

I chose the 2nd option because it implies less communication about things already known. Rooms are not that easy to handle because of room objects. As you know, some are randomly created. The problem is that some rooms have interactions with creatures. So if we leave the room objects creation to the client, we might end up in a situation were a blackmistress goes to get tortured somewhere and the torturing machine is not at the same place :)

Concerning the API, yes, we could change the names. But as I said in the forum, I think the gamemap/client/server deserves a wiki to explain how they work and most important, how they should be used so that people know that if they include ODFrameListener in ODServer.cpp, they are most likely doing something bad :)

Concerning changing room absorbtion logic, we could considere to keep the old room and only add some new tiles to it. But as I said, It will not be that easy because it could end up removing/recreating room objects.
I think we should see later if it is needed when we will have fixed the not shown tiles problem.

**Comment by Bertram25** [comment] 2014-08-08 12:22
Yep, considering all the constraints, it's amazing at which speed you were able to deal with all that. :)
Thanks also for answering all my sometime silly questions.

> Concerning the API, yes, we could change the names. But as I said in the forum, I think the gamemap/client/server deserves a wiki to explain how they work and most important, how they should be used so that people know that if they include ODFrameListener in ODServer.cpp, they are most likely doing something bad :)

I'm all for documentation, but from experience, the doc should lie within the code at first, even a short one. So developers too lazy to even open the wiki won't have excuse or reasons to add bad things. I am of the kind who love self-explanatory stuff.

> I think we should see later if it is needed when we will have fixed the not shown tiles problem.

Sure. (You know me. I'm the old bear always planning ahead.) ;)

It's true the room logic is complicated. From all I can see, if we want to be perfectly in sync, and not get you and me burnt out by all this, maybe the server should even tell the client where to put room objects and how.
Again, not forcefully now, but this might be a nice design simplification for later.

Regards,

**Comment by hwoarangmy** [comment] 2014-08-08 13:26
maybe the server should even tell the client where to put room objects and how.
 => It's already done ;)
That's just the room absorbtion that was a little bit more tricky but from what I've seen, it does work now.

**Comment by Bertram25** [comment] 2014-08-08 13:55
> It's already done ;)
> That's just the room absorbtion that was a little bit more tricky but from what I've seen, it does work now.

Wait, what? Already? :D \Ö/

**Comment by hwoarangmy** [comment] 2014-08-08 14:44
No, no, sorry, I didn't meant that I've done anything. Room absorption is supposed to work in the current code (just like room objects managed by the server) and I've done nothing more for this. Sorry, I still don't know what is the problem you have since I cannot reproduce it :(

**Comment by Bertram25** [comment] 2014-08-08 14:59
Np. I'll add logs spying room names and we'll see. ;)

**Comment by Bertram25** [comment] 2014-08-08 20:28
I deleted my latest comment as it was wrong, sorry again.

**Comment by Bertram25** [comment] 2014-08-08 20:35
Now the good log:

```
Log: TestSinglePlayerSmall.level (Single player)

Map loading...
createRoom(): Server : DungeonTemple_1
createRoom(): Server : Treasury_2
createRoom(): Server : Portal_3
createRoom(): Server : Portal_4
createRoom(): Server : Treasury_5
createRoom(): Server : DungeonTemple_6
createRoom(): Server : DungeonTemple_7
createRoom(): Server : Treasury_8
createRoom(): Server : Portal_9
createRoom(): Server : DungeonTemple_10
createRoom(): Server : Portal_11
createRoom(): Server : Treasury_12
...
createRoom(): Client : DungeonTemple_1
createRoom(): Client : Treasury_2
createRoom(): Client : Portal_3
createRoom(): Client : Portal_4
createRoom(): Client : Treasury_5
createRoom(): Client : DungeonTemple_6
createRoom(): Client : DungeonTemple_7
createRoom(): Client : Treasury_8
createRoom(): Client : Portal_9
createRoom(): Client : DungeonTemple_10
createRoom(): Client : Portal_11
createRoom(): Client : Treasury_12
... (All those rooms are shown correctly on the client, btw)

Render Manager create room requests:
Here below the rooms which have a client game map as parent, are creating the nodes:
This is perfectly fine so far.

RR: Create room tile: from client (game map): DungeonTemple_1_7_7
RR: Create room tile: from client: DungeonTemple_1_7_8
RR: Create room tile: from client: DungeonTemple_1_7_9
RR: Create room tile: from client: DungeonTemple_1_7_10
RR: Create room tile: from client: DungeonTemple_1_7_11
RR: Create room tile: from client: DungeonTemple_1_8_7
RR: Create room tile: from client: DungeonTemple_1_8_8
RR: Create room tile: from client: DungeonTemple_1_8_9
RR: Create room tile: from client: DungeonTemple_1_8_10
RR: Create room tile: from client: DungeonTemple_1_8_11
RR: Create room tile: from client: DungeonTemple_1_9_7
RR: Create room tile: from client: DungeonTemple_1_9_8
RR: Create room tile: from client: DungeonTemple_1_9_9
RR: Create room tile: from client: DungeonTemple_1_9_10
RR: Create room tile: from client: DungeonTemple_1_9_11
RR: Create room tile: from client: DungeonTemple_1_10_7
RR: Create room tile: from client: DungeonTemple_1_10_8
RR: Create room tile: from client: DungeonTemple_1_10_9
RR: Create room tile: from client: DungeonTemple_1_10_10
RR: Create room tile: from client: DungeonTemple_1_10_11
RR: Create room tile: from client: DungeonTemple_1_11_7
RR: Create room tile: from client: DungeonTemple_1_11_8
RR: Create room tile: from client: DungeonTemple_1_11_9
RR: Create room tile: from client: DungeonTemple_1_11_10
RR: Create room tile: from client: DungeonTemple_1_11_11
Mesh: Loading Treasury.mesh.
RR: Create room tile: from client: Treasury_2_12_7
RR: Create room tile: from client: Treasury_2_12_8
RR: Create room tile: from client: Treasury_2_12_9
Mesh: Loading Portal.mesh.
RR: Create room tile: from client: Portal_3_7_12
RR: Create room tile: from client: Portal_3_7_13
RR: Create room tile: from client: Portal_3_7_14
RR: Create room tile: from client: Portal_3_8_12
RR: Create room tile: from client: Portal_3_8_13
RR: Create room tile: from client: Portal_3_8_14
RR: Create room tile: from client: Portal_3_9_12
RR: Create room tile: from client: Portal_3_9_13
RR: Create room tile: from client: Portal_3_9_14
RR: Create room tile: from client: Portal_4_7_42
RR: Create room tile: from client: Portal_4_7_43
RR: Create room tile: from client: Portal_4_7_44
RR: Create room tile: from client: Portal_4_8_42
RR: Create room tile: from client: Portal_4_8_43
RR: Create room tile: from client: Portal_4_8_44
RR: Create room tile: from client: Portal_4_9_42
RR: Create room tile: from client: Portal_4_9_43
RR: Create room tile: from client: Portal_4_9_44
RR: Create room tile: from client: Treasury_5_12_37
RR: Create room tile: from client: Treasury_5_12_38
RR: Create room tile: from client: Treasury_5_12_39
RR: Create room tile: from client: DungeonTemple_6_7_37
RR: Create room tile: from client: DungeonTemple_6_7_38
RR: Create room tile: from client: DungeonTemple_6_7_39
RR: Create room tile: from client: DungeonTemple_6_7_40
RR: Create room tile: from client: DungeonTemple_6_7_41
RR: Create room tile: from client: DungeonTemple_6_8_37
RR: Create room tile: from client: DungeonTemple_6_8_38
RR: Create room tile: from client: DungeonTemple_6_8_39
RR: Create room tile: from client: DungeonTemple_6_8_40
RR: Create room tile: from client: DungeonTemple_6_8_41
RR: Create room tile: from client: DungeonTemple_6_9_37
RR: Create room tile: from client: DungeonTemple_6_9_38
RR: Create room tile: from client: DungeonTemple_6_9_39
RR: Create room tile: from client: DungeonTemple_6_9_40
RR: Create room tile: from client: DungeonTemple_6_9_41
RR: Create room tile: from client: DungeonTemple_6_10_37
RR: Create room tile: from client: DungeonTemple_6_10_38
RR: Create room tile: from client: DungeonTemple_6_10_39
RR: Create room tile: from client: DungeonTemple_6_10_40
RR: Create room tile: from client: DungeonTemple_6_10_41
RR: Create room tile: from client: DungeonTemple_6_11_37
RR: Create room tile: from client: DungeonTemple_6_11_38
RR: Create room tile: from client: DungeonTemple_6_11_39
RR: Create room tile: from client: DungeonTemple_6_11_40
RR: Create room tile: from client: DungeonTemple_6_11_41
RR: Create room tile: from client: DungeonTemple_7_37_7
RR: Create room tile: from client: DungeonTemple_7_37_8
RR: Create room tile: from client: DungeonTemple_7_37_9
RR: Create room tile: from client: DungeonTemple_7_37_10
RR: Create room tile: from client: DungeonTemple_7_37_11
RR: Create room tile: from client: DungeonTemple_7_38_7
RR: Create room tile: from client: DungeonTemple_7_38_8
RR: Create room tile: from client: DungeonTemple_7_38_9
RR: Create room tile: from client: DungeonTemple_7_38_10
RR: Create room tile: from client: DungeonTemple_7_38_11
RR: Create room tile: from client: DungeonTemple_7_39_7
RR: Create room tile: from client: DungeonTemple_7_39_8
RR: Create room tile: from client: DungeonTemple_7_39_9
RR: Create room tile: from client: DungeonTemple_7_39_10
RR: Create room tile: from client: DungeonTemple_7_39_11
RR: Create room tile: from client: DungeonTemple_7_40_7
RR: Create room tile: from client: DungeonTemple_7_40_8
RR: Create room tile: from client: DungeonTemple_7_40_9
RR: Create room tile: from client: DungeonTemple_7_40_10
RR: Create room tile: from client: DungeonTemple_7_40_11
RR: Create room tile: from client: DungeonTemple_7_41_7
RR: Create room tile: from client: DungeonTemple_7_41_8
RR: Create room tile: from client: DungeonTemple_7_41_9
RR: Create room tile: from client: DungeonTemple_7_41_10
RR: Create room tile: from client: DungeonTemple_7_41_11
RR: Create room tile: from client: Treasury_8_42_7
RR: Create room tile: from client: Treasury_8_42_8
RR: Create room tile: from client: Treasury_8_42_9
RR: Create room tile: from client: Portal_9_37_12
RR: Create room tile: from client: Portal_9_37_13
RR: Create room tile: from client: Portal_9_37_14
RR: Create room tile: from client: Portal_9_38_12
RR: Create room tile: from client: Portal_9_38_13
RR: Create room tile: from client: Portal_9_38_14
RR: Create room tile: from client: Portal_9_39_12
RR: Create room tile: from client: Portal_9_39_13
RR: Create room tile: from client: Portal_9_39_14
RR: Create room tile: from client: DungeonTemple_10_37_37
RR: Create room tile: from client: DungeonTemple_10_37_38
RR: Create room tile: from client: DungeonTemple_10_37_39
RR: Create room tile: from client: DungeonTemple_10_37_40
RR: Create room tile: from client: DungeonTemple_10_37_41
RR: Create room tile: from client: DungeonTemple_10_38_37
RR: Create room tile: from client: DungeonTemple_10_38_38
RR: Create room tile: from client: DungeonTemple_10_38_39
RR: Create room tile: from client: DungeonTemple_10_38_40
RR: Create room tile: from client: DungeonTemple_10_38_41
RR: Create room tile: from client: DungeonTemple_10_39_37
RR: Create room tile: from client: DungeonTemple_10_39_38
RR: Create room tile: from client: DungeonTemple_10_39_39
RR: Create room tile: from client: DungeonTemple_10_39_40
RR: Create room tile: from client: DungeonTemple_10_39_41
RR: Create room tile: from client: DungeonTemple_10_40_37
RR: Create room tile: from client: DungeonTemple_10_40_38
RR: Create room tile: from client: DungeonTemple_10_40_39
RR: Create room tile: from client: DungeonTemple_10_40_40
RR: Create room tile: from client: DungeonTemple_10_40_41
RR: Create room tile: from client: DungeonTemple_10_41_37
RR: Create room tile: from client: DungeonTemple_10_41_38
RR: Create room tile: from client: DungeonTemple_10_41_39
RR: Create room tile: from client: DungeonTemple_10_41_40
RR: Create room tile: from client: DungeonTemple_10_41_41
RR: Create room tile: from client: Portal_11_37_42
RR: Create room tile: from client: Portal_11_37_43
RR: Create room tile: from client: Portal_11_37_44
RR: Create room tile: from client: Portal_11_38_42
RR: Create room tile: from client: Portal_11_38_43
RR: Create room tile: from client: Portal_11_38_44
RR: Create room tile: from client: Portal_11_39_42
RR: Create room tile: from client: Portal_11_39_43
RR: Create room tile: from client: Portal_11_39_44
RR: Create room tile: from client: Treasury_12_42_37
RR: Create room tile: from client: Treasury_12_42_38
RR: Create room tile: from client: Treasury_12_42_39

- Here I build a new room unconnected to the other one:
createRoom(): Server : Treasury_13
...
createRoom(): Client : Treasury_13

- note that there is no tile nor node creation render requests ?

...

- Here I build a new room but connected to the other one:
createRoom(): Server : Treasury_14
...
createRoom(): Client : Treasury_14
*** ERROR: Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException):
SceneNode 'Treasury_14_12_7_node' not found. in SceneManager::getSceneNode at /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 920)
```

**Comment by Bertram25** [comment] 2014-08-08 20:37
My current conclusion is that the render requests of rooms made while in game aren't triggered/processed, hence not creating nodes and making the game crash when anything tries to interact with non-existing nodes and room tiles.

**Comment by akien-mga** [comment] 2014-08-08 21:11
I'm on #opendungeons, feel free to stop by :-)

**Comment by Bertram25** [comment] 2014-08-08 21:15
Latest addition:
When creating the unconnected room, the meshLocal() functions are called for the client game map

```
createRoom(): Client : Treasury_14
GameEntity::CreateMesh()
Room::CreateMeshLocal()
GameEntity::CreateMeshLocal()
Room::CreateMeshLocal() client for tiles number: 0
```

But, the tile number to create is 0, not 1.

**Comment by hwoarangmy** [comment] 2014-08-08 21:53
Rooms are built by creating 1 per 1 evey tile on which are the room. From what I see in your log, it seems the room has no tile.
Because the problem seems architecture related, I would guess it comes from the ODPacket sent from the server to the client. Probably the vector size. If you want to bet a beer, I would say that the size_type returned by vector.size() is not an int on your systems.
So, the correction would be to change https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L174
Change :
serverNotification->packet << intType << player->getSeat()->getColor() << coveredTiles.size();
=>
int nbTiles = coveredTiles.size();
serverNotification->packet << intType << player->getSeat()->getColor() << nbTiles;

If it fixes the bug, I will make a patch and go through the other messages to make sure I always use the same type when sending/getting to/from ODPacket

**Comment by hwoarangmy** [comment] 2014-08-08 21:53
PS : thanks for the feedback :)
PS2 : It would also explain the marked tiles not shown
PS3 : I'm almost sure I'm right so I'm gonna do the patch right now

**Comment by Bertram25** [comment] 2014-08-08 22:00
@hwoarangmy you are, I didn't see your comment and fixed it with this:
            uint32_t nbTiles = static_cast<uint32_t>(coveredTiles.size());
            serverNotification->packet << intType << player->getSeat()->getColor() << nbTiles;

**Comment by Bertram25** [comment] 2014-08-08 22:03
@hwoarangmy 
PS: You're welcome :) I'm happy :D 
PS2: I think it too
PS3: Wanna do the patch or will I?
PS4: I am on IRC atm.

**Closed as completed** 2014-08-08 23:02 UTC
Labels: Bug, Single-Player, Linux
