### ISSUE TITLE
Warnings with _cegui_ogre_X textures

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#262] opened 2014-10-23 09:43 UTC
Some warnings with current dev branch:

```
WARNING: Texture instance '_cegui_ogre_6' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_3' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_7' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_5' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_1' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
```

```
WARNING: Texture instance 'miniMapOgreTexture' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_0' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_2' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
WARNING: Texture instance '_cegui_ogre_4' was defined as manually loaded, but no manual loader was provided. This Resource will be lost if it has to be reloaded.
```

**Comment by Bertram25** [comment] 2014-10-23 14:55
Thanks for reporting warnings. :)

Duplicate of #29 . Yet, the warning list is more complete here while the explanation is more complete in this in the former one.
May copy/paste the warnings list there and close this one?

**Comment by akien-mga** [comment] 2014-10-23 14:59
Done :-)

**Closed as completed** 2014-10-23 14:59 UTC
Labels: Bug, Duplicate

**Comment by Bertram25** [comment] 2014-10-23 15:21
Thanks! :)
