### ISSUE TITLE
Normals for everything?

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#511] opened 2015-02-18 11:23 UTC
Normal maps for big things like portals and rooms are fine, but should i also made them for small elements like training dummies , library podiums, etc...?=

**Comment by Bertram25** [comment] 2015-02-18 11:27
@Danimal696 In a perfect world, I'd say yes, but it might cost a few more fps, so I'd say, as the true artist of the team, you should have the last word on that one.
If you think adding normals on certain elements isn't worth it, then I'm fine with your decision.

**Comment by hwoarangmy** [comment] 2015-02-18 11:55
Yes. It seems like normals have a pretty high cost on performances. Activating them have significantly lowered the FPS rate in my computer. In any case, is it possible to add some configuration to disable them ? That would allow the game to run with older computers. Moreover, that would allow to have 3 levels:
- No normal (for weak computers)
- Most important normals (creatures, walls, ground, ...) but not the room objects
- Everything

**Comment by Bertram25** [comment] 2015-02-18 12:26
I do think we should opt-out the Everything case and target a most important normals goal, as raised by @Danimal696 
As for disabling normals, it is simply about not starting the rtss handler, IMHO + a few tweaks I guess.

What do you think about it, everyone?

**Comment by Danimal696** [comment] 2015-02-19 14:23
ok, im setting for room tiles, creature models and big room elements that stand out a lot (like chimney from forge)

**Comment by hwoarangmy** [comment] 2015-02-19 14:53
Anyway, I guess there will always be a need for having as detailed graphics as possible. And if we feel it is really too heavy, we will find a way to disable normals for not mandatory elements (for example by having different materials folders).

**Comment by Danimal696** [comment] 2015-02-19 14:57
There is a fair bit of work to making normals for each model, optimistically all models could have them, so what the best course of action?
Make models for everything and setting a switch for using them? or normals for just the important ones?

**Comment by hwoarangmy** [comment] 2015-02-19 15:45
IMHO, normals for more important things. If it is time consuming, we will see for the rest later. First things first ^^

**Comment by Bertram25** [comment] 2015-02-19 15:56
Yeah, it's kinda the big task. I can span on several release if it's too much, so don't worry too much, one thing at a time. You can fix whatever you see is most important first, for instance. :)

**Comment by Bertram25** [comment] 2015-02-23 00:17
I guess the issue question was settled. Yet, shouldn't we open an issue about optionally disable normals or should we wait for @Danimal696 to more or less finish the task?
@oyvindln @hwoarangmy

**Comment by Bertram25** [comment] 2015-03-18 13:15
To make this issue clearer, I'd propose to:
1. Let @Danimal696 add normals on models little by little as a background task like he's been doing since some time now.
2. Make it clear that this issue is about optionally disabling the RTSS at (re)start and depends on the settings window support.

WDYT?

**Comment by akien-mga** [comment] 2015-03-18 13:30
That sounds sensible to me. IMO we could consider that every model could benefit from backgrounds, but the artist's priority should be the bigger/most used models.
The we should have an option to disable the RTSS, and depending on the feedback from our users, we could for a later milestone have an option to disable some of the normals for a subset of the objects (that would require the ability to categorise materials, and to make their normals constrained by a variable, so I'm talking about long term ++ ;).

**Comment by Bertram25** [comment] 2015-03-18 14:10
> The we should have an option to disable the RTSS, and depending on the feedback from our users, we could for a later milestone have an option to disable some of the normals for a subset of the objects (that would require the ability to categorise materials, and to make their normals constrained by a variable, so I'm talking about long term ++ ;).

I must say I do hope switching to the Ogre 2.1+ HLMS one day too, so that's not something easy to sort out, yet. The switch to Ogre 2.x should sort out some performance problems while surely add other ones. ;) So yeah, it's not around the corner to be solved yet.

**Comment by alketii** [comment] 2015-03-18 14:12
What I've heard, ogre 2.x has a bit low fps.

**Comment by Bertram25** [comment] 2015-03-18 14:28
> What I've heard, ogre 2.x has a bit low fps.

OMG, people are watching us. O.O'

More seriously, welcome @alketii :)
From what I've read myself, Ogre 1.x is, and on Ogre 2.x, you can still use the v1 mechanisms, which are not fast either. The engine is still experimental and has got problems when using a lot of light sources for instance + [add an inifinity of other problems an alpha branch can give].
That said, the progress being made are impressive and I do hope that one day they will reach an interesting state enough for us to make the switch and test whether it is actually faster. :)

**Comment by oyvindln** [comment] 2015-03-18 14:40
From what I can read, Ogre 2.x seems to be [dropping support for pre-DX10](http://www.ogre3d.org/forums/viewtopic.php?f=25&t=82743&p=514477&sid=d73f9ebb2b5b6cb1cbd9a8660363381e#p514474) cards though, not sure if we want to do that any time soon. (At least I won't be able to do that without upgrading my system.) Though on the bright side, it seems the HLMS [will be available](http://www.ogre3d.org/2015/02/10/hlms-pbs-online-editor-sponsored-by-coderabbit-gmbh#more-2354) in the 1.10 branch as well.

**Comment by Bertram25** [comment] 2015-03-18 15:00
> From what I can read, Ogre 2.x seems to be dropping support for pre-DX10 cards though, not sure if we want to do that any time soon.

Yeah, but wasn't it a temporary decision to prioritize the scope of it? Or is it something left to 1.x users?

> on the bright side, it seems the HLMS will be available in the 1.10 branch as well.

Yeah, we'll be able to experiment with the new system sooner than making a potential switch. :)

**Comment by Bertram25** [comment] 2015-04-04 09:10
Duplicate of #458

**Closed as completed** 2015-04-04 09:10 UTC
Labels: Discussion, Game content
