### ISSUE TITLE
Segfault in Seat::notifyVisionOnTile

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#385] opened 2014-12-17 16:53 UTC
Texture: Dirt_darkE.png: Loading 1 faces(PF_R8G8B8,256x256x1) with 8 hardware generated mipmaps from Image. Internal format is PF_X8R8G8B8,256x256x1.
Mesh: Loading Dirt_10001111.mesh.
Mesh: Loading Dirt_10000011.mesh.
Mesh: Loading Dirt_11111111.mesh.

Computing turn 1SERVER - Adding Creature Kobold1
SERVER - Adding Creature Kobold2
SERVER - Adding Creature Kobold3
signal 11 (Segmentation fault), address is 0x8c from 0x8101312

[bt]: (1) ./opendungeons : Seat::notifyVisionOnTile(Tile_)+0x12 [0x8101312]
[bt]: (2) ./opendungeons : Seat::notifyVisionOnTile(Tile_)+0x12 [0x8101312]
[bt]: (3) ./opendungeons : Tile::computeVisibleTiles()+0x27 [0x80f6e27]
[bt]: (4) ./opendungeons : GameMap::doMiscUpkeep()+0x760 [0x810e990]
[bt]: (5) ./opendungeons : GameMap::doTurn()+0x53 [0x810f313]
[bt]: (6) ./opendungeons : ODServer::startNewTurn(double)+0x2dc [0x8153aac]
[bt]: (7) ./opendungeons : ODServer::serverThread()+0x1b4 [0x8155da4]
[bt]: (8) /usr/lib/libsfml-system.so.2 : sf::Thread::run()+0x12 [0xb6b34562]
[bt]: (9) /usr/lib/libsfml-system.so.2 : +0x730f [0xb6b3530f]
[bt]: (10) /lib/libpthread.so.0 : +0x6b5e [0xb6afeb5e]
[bt]: (11) /lib/libc.so.6 : clone+0x5e [0xb690fb2e]

**Comment by Bertram25** [comment] 2014-12-17 17:13
The function is implemented here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/game/Seat.cpp#L371

That's something funny as the function shouldn't be able to segfault at all even with flawed pointer values, unless mTilesWithVision iteration itself makes it crash.
By commenting one line after another, can you tell us which statement makes the game crash?

**Comment by hwoarangmy** [comment] 2014-12-17 20:59
I've already seen bugs like this happening when a vector is used (adding or removing items) while it is being iterated. But since Seats are specific to 1 gamemap only, I don't see how this can happen unless we let an entity from the server gamemap being rendered. And even if it was the case, mTilesWithVision is not the most used...

**Comment by hwoarangmy** [comment] 2014-12-17 21:06
I've just thought that it might be the Seat that is null.
@tomluchowski Thanks for reporting a bug. But when you do so, could you please also tell us a little bit of context ?
At least:
- The map you launched
- How much time elapsed when it happened (from the creature number, it seems to be at game start in this case)
- What were you doing when it happened before launching the game ? Were you in the editor ? Have you tried to launch another map previously ?

Thanks

**Comment by hwoarangmy** [comment] 2014-12-17 21:09
I've had a look and seen no access outside the server thread to this vector. My guess is that it is Seat that is null.
Could you also confirm if the map you launched is original or have you changed something ?

**Comment by Bertram25** [comment] 2014-12-17 21:46
Ah true. The seat being null could explain it all.

**Comment by Bertram25** [comment] 2014-12-17 23:00
Let's give @tomluchowski a few days to answer unless one of us can reproduce.
Then, if the issue is the sole left, I'll move it to 0.5.0 as we shouldn't block the release for an issue we can't reproduce.

**Comment by hwoarangmy** [comment] 2014-12-18 00:38
I've reproduced the bug. It's systematic on BigTestMap and as expected because there is a tile claimed with a null seat. If we allow to have claimed tiles without seat, I will add a check in the tile vision computation. If not, I will change the level.

Concerning the release, it only impacts the PR I've done on seat vision so there should be no problem as it is not in the stable branch AFAIK.

**Comment by Bertram25** [comment] 2014-12-18 10:49
> Concerning the release, it only impacts the PR I've done on seat vision so there should be no problem as it is not in the stable branch AFAIK.

But IMHO, it should be. The stable branch should contain the latest balancing changes + the few fixes we have done so far for the RC1.
Is it possible to "de-claim" a tile if the corresponding seat won't exist at load time? I just can't see why it would be useful anyway.

**Comment by Bertram25** [comment] 2014-12-18 10:50
@hwoarangmy Btw, thanks for taking the time to get how to reproduce it. :)
It's always cool to know where some flaws are from, before a release.

**Comment by hwoarangmy** [comment] 2014-12-18 12:49
ok. I will try to post a fix asap then.

**Comment by tomluchowski** [comment] 2014-12-18 13:37
Hard to say , first it happens on all the maps in Single player ( skirmish ) mode . 
I don't change the seat settings , I just accept the default settings ( seat id 1 -- player , always some seat inactive ... ) . Is it ever possible to change those settings ? 
EDIT : this happens on i386, hard to say the other machine, I got ISP issues....

**Comment by tomluchowski** [comment] 2014-12-18 13:47
Hm there is at least one map which works fine in here .  
Also one cannot click the button 'Back'  button after having the map choosen -- the game crashes : 
http://pastebin.com/nfPJwhs3

**Comment by akien-mga** [comment] 2014-12-18 13:57
>  Also one cannot click the button 'Back' button after having the map choosen -- the game crashes

I confirm that such glitches happen from time to time, in my case systematically after you've loaded and close several maps several times (or one map several times, or several maps one time... :-P), usually quickly after each other (i.e. when doing quick tests).

I guess some things are not cleaned properly when closing a map, or when closing it while it's still loading content.

**Comment by Bertram25** [comment] 2014-12-18 14:03
Nice catch. I guess this is a separate issue slightly less urgent to fix. I'd open an issue for 0.5.0 if you're ok with it.

**Comment by Bertram25** [comment] 2014-12-18 16:25
Created #386

**Closed as completed** 2014-12-18 18:01 UTC
Labels: Bug, Discussion
