### ISSUE TITLE
does not compile on arm

### ISSUE THREAD

**Issue by paroj** [OpenDungeons/OpenDungeons#1305] opened 2019-02-16 18:23 UTC
```
[ 99%] Building CXX object CMakeFiles/opendungeons.dir/source/utils/StackTraceUnix.cpp.o
/build/opendungeons/parts/opendungeons/src/source/utils/StackTraceUnix.cpp:122:2: error: #error Unsupported architecture.
 #error Unsupported architecture. // TODO: Add support for other arch.
  ^
/build/opendungeons/parts/opendungeons/src/source/utils/StackTraceUnix.cpp: In static member function ‘static void StackTracePrintPrivateData::critErrHandler(int, siginfo_t*, void*)’:
/build/opendungeons/parts/opendungeons/src/source/utils/StackTraceUnix.cpp:107:21: error: unused variable ‘uc’ [-Werror=unused-variable]
     sig_ucontext_t* uc = static_cast<sig_ucontext_t*>(ucontext);
                     ^
cc1plus: all warnings being treated as errors
```

**Comment by akien-mga** [comment] 2019-02-18 13:37
Duplicate of #1247.

**Closed as completed by akien-mga** 2019-02-18 13:37 UTC
Labels: Duplicate
