### ISSUE TITLE
Crash on missile spawn.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#120] opened 2014-09-01 07:14 UTC
As reported by @Danimal696 here: http://forum.freegamedev.net/viewtopic.php?f=37&t=5786

The crash exception log is:
`Internal Ogre 3d exception: SceneNode "MissileObject_Missile_Object_1_node" not found. ...`
This happens on the 2014-08-20 rolling release windows binary.

Some work has been done on units names so this might already be fixed in master, but we have to make sure.

**Comment by hwoarangmy** [comment] 2014-09-01 09:10
I think it is already fixed but I am waiting for @Danimal696 to add more information on how to reproduce the bug.

**Comment by Bertram25** [comment] 2014-09-01 10:11
> I think it is already fixed but I am waiting for @Danimal696 to add more information on how to reproduce the bug.

I think it too. AFAIK, to reproduce the bug, you have to place cannons within a level file (so they are loaded at map start) such as in the oldtest.level file, and attract enemy creatures to make the cannon fire.
The crash should happen at that moment, or no more. :)
@Danimal696 may have more info, though.

**Comment by hwoarangmy** [comment] 2014-09-01 12:07
It only happens on canons loaded from file ? I've never tried such cases...

**Comment by Bertram25** [comment] 2014-09-01 13:01
> It only happens on canons loaded from file ?

I don't know yet, but I reproduced only that way. And I didn't want to interfere or tell things I haven't actually tested.

**Comment by hwoarangmy** [comment] 2014-09-01 14:01
Well, I have already tested quite a lot canons and didn't see this crash. I remember having fixed a bug where the missile object number was wrongly handled. But I don't remember if it was after or before the new release...

**Comment by akien-mga** [comment] 2014-09-01 14:05
The release was on August 21st around 1 a.m., you can check if your commit was after that :-)

**Comment by Danimal696** [comment] 2014-09-01 14:05
> It only happens on canons loaded from file

Hi guys, yes, that the case; i tried and it happened each time a cannon tried to fire to something. im sure thats the cause.

**Comment by Bertram25** [comment] 2014-09-01 14:30
Ok, then the test is simple enough. :)
If we can test @Danimal696 's level and it doesn't crash when a cannon is firing on master, then the bug is fixed. I'm eager to see that level anyway. :)

@Danimal696 
If the bug is indeed fixed, I'll upload a new binary for you asap, so you can go ahead with the level more freely. :)

**Comment by Danimal696** [comment] 2014-09-01 15:19
Thanks, but everything would go smoother if the editor worked in the next exe so i dont have to jump between two OD versions

**Comment by Bertram25** [comment] 2014-09-01 15:34
> Thanks, but everything would go smoother if the editor worked in the next exe so i dont have to jump between two OD versions

Now you tell it, it seems broken on the windows binary:
@hwoarangmy Are you still on the level editor menu or can I have a go at it once I've fixed my other pull request?

**Comment by Bertram25** [comment] 2014-09-01 15:38
@Danimal696 You're right, we should have a round at easing level edition so that you can work without too much annoyance but I can't promise anything right now. See #22 #17 #18

**Comment by hwoarangmy** [comment] 2014-09-01 19:00
> Are you still on the level editor menu or can I have a go at it once I've fixed my other pull request?

I've never worked on the editor. So, you can do as you want.
But if you want some help to go faster, feel free to ask :)

**Comment by hwoarangmy** [comment] 2014-09-02 21:03
Bertram tested with Danimal's map and it seems like the crash do not happen anymore, I close this issue

**Closed as completed by hwoarangmy** 2014-09-02 21:03 UTC
Labels: Bug
