### ISSUE TITLE
Destroying enemy temple does not have the desired effects

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1173] opened 2016-04-24 00:13 UTC
I've played the level 'Duel to death' and managed to kill the green temple in build 20160402.

At this point I expected several things to happen:
1) The game won
2) No new creatures coming from the green portal
3) All green creatures dying or fleeing to the nearest portal
4) My own creatures to stop destroying the green rooms so I could claim what was left and they could go 'home' to rest
5) Green path to become unclaimed and green walls to become unfortified

All 5 of these assumptions proved to be incorrect. I think these expectations should have been met.

**Comment by hwoarangmy** [comment] 2016-04-24 09:20
This has already been discussed. Excepted point 2, it is the expected behaviour. The reason is multiplayer gaming.

1 - Not implemented yet. Game never stops. Probably for the next release.
2 - Strange, they should not. Do you have the logs ?
3 - We have chosen to let dead keepers be allowed to use their creatures (ie pickup/drop) even when the dungeon heart is destroyed so that in multiplayer, while their allies are alive, they have something to do
4 - ATM, it is not planned to allow claiming enemy rooms. However, it is open to discussion and could be something in the game settings like KOing creatures for example.
5 - The problem here is that in multiplayer, you cannot claim allied claimed tiles. That means that if your ally is weak, if you have a common claimed wall, you will be exposed.

Note that there is no consensus about the issues you are reporting. As a first step, we choose to implement things on the simplest way code-wise (some choices being discutable but logical). This way, we can focus on more important stuff for a 1.0 release.

**Comment by Loobinex** [comment] 2016-04-24 10:33
2) Sorry, no.
3) As a consequence you can still die to a player after you have defeated him. Especially problematic if you have more than one adversary. A player without a dungeon heart should no longer be a threat. For coop you could allow the defeated player to help micromanage the surviving players dungeon.
5) It sounds like a good thing - a fun strategic consideration - if a defeated ally gives you an exposed flank.

**Comment by Bertram25** [comment] 2016-04-24 21:23
> 3) As a consequence you can still die to a player after you have defeated him. Especially problematic if you have more than one adversary. A player without a dungeon heart should no longer be a threat. For coop you could allow the defeated player to help micromanage the surviving players dungeon.

Funny. I don't find this is a problem, except in campaign, which is a type of gameplay we didn't enter yet.

**Comment by hwoarangmy** [comment] 2016-04-25 08:35
> Funny. I don't find this is a problem, except in campaign, which is a type of gameplay we didn't enter yet.

Well, for me, it is not a problem even for campaign. If you succeed to kill your opponent dungeon heart and that it is your only goal, the game will stop anyway and bring you to victory screen. If there is still something to do and you are not carefull enough with your dungeon heart, you will loose and that's acceptable IMHO.

> For coop you could allow the defeated player to help micromanage the surviving players dungeon.

Here, you are hitting something. In multiplayer, allied players cannot pickup each others creatures. And, when an ally loose, I'm not sure I will see as a good think that he may pickup my creatures without me allowing it.

**Comment by hwoarangmy** [comment] 2016-04-25 19:10
I've had a look at 3 and I confirm there is a bug. Fix is on its way

**Comment by Loobinex** [comment] 2016-04-25 21:02
You mean number 2 - spawning creatures after destruction of the temple.

**Comment by hwoarangmy** [comment] 2016-04-25 21:06
yep, 2 you're right

**Comment by Bertram25** [comment] 2016-04-25 22:49
Is there anything left we agreed to change here?

**Comment by Loobinex** [comment] 2016-04-25 22:56
The first point - winning the level on destruction of the temple.

Also, on Issue #1171 there's sort of agreement on point 5 - unclaim tiles/unfortify walls on defeat. My suggestion is to move discussion about the 5th point here and reject #1171.

**Comment by hwoarangmy** [comment] 2016-04-26 07:48
Point 1 is obvious but not implemented yet. Concerning unfortifying walls when a player is defeated, it is more discussed in #1171 than here so let's close this issue and continue on the other (changing title)

**Closed as completed by hwoarangmy** 2016-04-26 07:48 UTC
Labels: Enhancement

**Comment by Bertram25** [comment] 2016-04-29 20:48
Set to 0.7 as @hwoarangmy implemented the bits still from this one.
