### ISSUE TITLE
New portal support

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#323] opened 2014-11-16 11:25 UTC
From here: http://forum.freegamedev.net/viewtopic.php?p=60904#p60904

The former portal can be removed as the current one won't be used for other needs.

Also, the new portal doesn't have ground tiles so this will have to be figured out in the code as well.
Last but not least, certain maps were placing the former portal in a way that isn't compatible with the new one. 3x3 vs 2x3 and the maps will have to be fixed as well.

**Comment by Danimal696** [comment] 2014-11-16 13:15
Its 3x3, opossed to 2x3 of the old one; i can also look for some unique tiles for it but i would prefer it to be like the boulder and show only the normal tiles below (be it claimed or unclaimed)

**Comment by Bertram25** [comment] 2014-11-17 07:57
> Its 3x3, opossed to 2x3 of the old one;

Oops, I'll fix the description.

**Comment by Bertram25** [comment] 2014-11-17 07:58
> i can also look for some unique tiles for it but i would prefer it to be like the boulder and show only the normal tiles below (be it claimed or unclaimed)

IMHO, we can manage without. But #277 should be dealt with, along with this one, IMHO.

**Comment by hwoarangmy** [comment] 2014-11-17 08:32
> i would prefer it to be like the boulder and show only the normal tiles below

I'm not sure we should handle that that way because there is a huge difference between traps and the portal. There is 1 mesh per trap and it disapears when killed. Which means that the mesh allows to see if the trap is alive or not.
Concerning the portal, not having ground tile would mean you will not see if some have been destroyed or not. Moreover, in game, you will see creatures attack tiles that you do not distinguish from normal claimed tiles...

**Comment by Bertram25** [comment] 2014-11-17 08:58
> I'm not sure we should handle that that way because there is a huge difference between traps and the portal. There is 1 mesh per trap and it disapears when killed. Which means that the mesh allows to see if the trap is alive or not.
> Concerning the portal, not having ground tile would mean you will not see if some have been destroyed or not. Moreover, in game, you will see creatures attack tiles that you do not distinguish from normal claimed tiles...

While this is very true, IMHO, the actual solution to this problem is to add different versions of the portal and display them according to the current damage amount. This would be way better and much more definite, IMO.

(The same logic could be done for the temple, btw.)
@Danimal696 @hwoarangmy Would you guys be ok with it? Would it be hard to add, say, two or three gradually broken versions of the portal?

**Comment by hwoarangmy** [comment] 2014-11-17 10:08
Again, the problem is that the room size if unknown and can be big. If the tiles are not different, we will see creatures attack normal tiles and it will seem weird.
That being said, changing the portal/dungeon temple according to its healt seems like a good idea to me. And if @Danimal696 says it's too much work to have other meshes for now, we might just resize it...

**Comment by Bertram25** [comment] 2014-11-17 10:24
> Again, the problem is that the room size if unknown and can be big. If the tiles are not different, we will see creatures attack normal tiles and it will seem weird.

That's something relevant indeed. IMHO, portals and temples should have a fixed size, or have specific ground tiles.
And specific ground tiles is compatible with having the portal object being gradually destructible.

Since we're in need of graphic resources, @Danimal696 will have the last word on this. ;)

**Comment by Danimal696** [comment] 2014-11-17 13:53
im not totally opposed to that, but do we really want to destroy portals the usual way?; i would prefer it the way dk and dk2 handled it, that its, evil portals are never destroyed, just captured like rooms, each new captured portal add some creature to your total max, so they are a resource to figth over. 
I can create a permanent portal for heroes as well (its just a visual difference, code would be the same as is now) and some minor portals that AI can use for sending enemy waves and are destructable. But even so, i think destruction should be by claiming all of it tiles (or it as a whole, not tile by tile), instead of melee/ranged damage.

**Comment by Bertram25** [comment] 2014-11-19 16:47
> But even so, i think destruction should be by claiming all of it tiles (or it as a whole, not tile by tile), instead of melee/ranged damage.

Arf, that's opposite to the currently followed design and will trigger some refactoring.

Here, you said:

> i would prefer it the way dk and dk2 handled it, that its, evil portals are never destroyed, just captured like rooms, each new captured portal add some creature to your total max, so they are a resource to figth over. 

I liked that logic as well, but also here you said:

>  and some minor portals that AI can use for sending enemy waves and are destructable.

Thus, we would have destructible rooms anyway.

Hence, as a longer term stuff and as more complete improvement, I'd propose this:
- Rooms are destroyed by fighter creatures like now. The first improvement I would see is that we could make the room disappear only when all tiles are "dead".
- Rooms can optionally be claimed by workers. (Personally, I do think this should be a skill obtained through research to add a bit of spice.) The room as a whole would then have to be claimed before becoming of the new team color.
  --> One question remaining: If someone starts destroying/claiming my room, I would add new tiles to it from time to time to prevent that as a last resort move, would this be acceptable?

Also, as this issue is still a bit vague, and would require refactoring anyway, I'd request it to be moved to later for now, along with #277 unless someone would take the latter now.

What do you think, everyone? (I'm adding @oyvindln and @akien-mga in the loop)

**Comment by Danimal696** [comment] 2014-11-19 17:21
its mostly to avoid people sniping enemy portals, its a much too important building to be lost so easily, while AI portals can be destroyed without worries if you find their constants raids annoying; but not by direct damage as of now, the claiming way its harder to achieve, thats the reason i proposed it.

**Comment by hwoarangmy** [comment] 2014-11-19 17:25
> Personally, I do think this should be a skill obtained through research to add a bit of spice.

Sounds like a good idea to me. I don't like being able to claim some rooms and destroy others. I think it would make things hard to understand for new players.

> Rooms are destroyed by fighter creatures like now. The first improvement I would see is that we could make the room disappear only when all tiles are "dead".

It would be easier for coders but:
- If creatures destroy half my dormitory and I manage to kill them. I won't be able to restore the room HP ?
- If I get attacked but I'm not looking, I won't know how healthy my room is ?

Concerning being able to claim ennemy rooms, I remember that there was an option in DK to choose if ennemies were to be killed or to be knocked out (for torturing/prison). We might have the same to choose between claiming or destroying ennemy rooms... IMHO, if we allow to claim rooms (by research or not), we will have to do something like that. Otherwise, it would be too hard to manage my creatures so that they kill the ennemy creatures but not the room they are in (if I am in an ennemy room, there will most likely be ennemy creatures lurking around)...

**Comment by Bertram25** [comment] 2014-11-19 17:47
> its mostly to avoid people sniping enemy portals, its a much too important building to be lost so easily, while AI portals can be destroyed without worries if you find their constants raids annoying; but not by direct damage as of now, the claiming way its harder to achieve, thats the reason i proposed it.

@Danimal696 Sure :) That's why the room claiming skill could be tasty to get. ;)

@hwoarangmy 
You're right about destroying rooms as a whole. It adds a lot of useless complexity. To stay compatible with @Danimal696 's proposal, I'd say that only the temples and the portals should be destroyable as a whole, and let the current logic for the other rooms.
Those rooms aren't restorable anyway, so they wouldn't heal, and we should use different room objects to show how damaged the room is.

Also, to stay balanced in term of gameplay, the portals and temples should have a fixed size when placing them in the editor. (Internally, I don't really care, but as for users, we should try not to make them place unfitting temple or portal room shapes.)

What do you think guys?

**Comment by Danimal696** [comment] 2014-11-19 17:48
In Dk the room claiming was made as a whole, so i think each connected room tile added some HP to a total and the imp efforts damaged it, if you tried but failed to claim a room, the HP started to slowly recover, so i guess adding new tiles would add more HP to the whole. You could try that tactic but save for the cheapest rooms its not a very effective one.

**Comment by Bertram25** [comment] 2014-11-20 08:47
A definite decision will have to be done I guess, not forcefully to copy DK, but to implement what we prefer. In the meanwhile, I'll upgrade the portals models and we should open a new forum thread to discuss and decide how we want to implement all that.

**Comment by Bertram25** [comment] 2014-11-25 09:39
Once the PR is merged, I'll move this one to 0.5.0.

**Comment by Bertram25** [comment] 2014-11-25 20:35
The portal definite logic is still to be decided. Moving to 0.5.0...

**Comment by hwoarangmy** [comment] 2014-11-25 20:43
I've had a look at the portal, it looks pretty nice. But the vortex is not really visible. IMHO, we should go for another animation when creature spawns...

**Comment by Danimal696** [comment] 2014-11-25 21:38
it suddenly contracts and then expand, think of something better?

**Comment by hwoarangmy** [comment] 2014-11-25 22:26
I meant removing the vortex and make the portal turn or add effects (fire/fireworks or something like that)

**Comment by Danimal696** [comment] 2014-11-26 14:38
i wonder, can the creature max number be configurable by level file, just like starting gold is?; this makes me think as well... if we ever wanted a hero campaign (or different keeper ones), all custom config files should be shipped with it instead of using a global config file always.
What i mean is we would need a new folder called "campaigns", and the game would looks for all needed config files inside of each unique campaign folder instead of using a global one.

**Comment by Bertram25** [comment] 2014-11-26 15:19
> What i mean is we would need a new folder called "campaigns", and the game would looks for all needed config files inside of each unique campaign folder instead of using a global one.

Yep, that's what I think also. Or even per level, IMHO. The global.cfg file is here to get the default fallback value though.

**Comment by hwoarangmy** [comment] 2014-11-26 15:21
Until now, we have used the following logic:
- Use the global config (for example creature classes)
- If overwritten (totally or partially) in the level file, use it

That's probably enough for a campaign (We will probably want to change different things for each levels). We just need to decide what is overwritable and what is not.

**Comment by akien-mga** [comment] 2014-11-26 15:28
Though @Danimal696 raises a valid point. When we design campaigns, we _might_ want to override the default config with a campaign-specific config that would be shared between all campaign levels. As said previously, this can already be done in the level files, but it would force to duplicate lots of config for a campaign with many levels using the same config changes.

That said, we are not there yet, so I don't think we need to implement something like that for now. Most likely the per-level overrides will be enough, unless @Danimal696 wants to rebalance all creatures for a given campaign ;-)

**Comment by hwoarangmy** [comment] 2014-11-26 15:32
I am not sure we will really want to do global changes for a whole campaign. But even if we do, the overwrite logic is already there so, to answer @Danimal696 's question, yes, it is possible to override. And if needed, we can add the needed to override everything for a campaign (by using a file include system for example).

**Comment by akien-mga** [comment] 2014-11-26 15:38
I like the file inclusion idea. But as you said, "if needed", let's not implement features that we don't need for now :-)

**Comment by Danimal696** [comment] 2014-12-01 10:52
now i understand hwoarangmy when he said the portal has a funny vortex, rigth now its using the wrong animation by pure chance. It has two animations: 

Idle - to be looped, soft circling ; 
Triggered - when creature appears, violent expanding/contracting

it would be good if any of you fix it

**Comment by Bertram25** [comment] 2014-12-01 11:12
> Idle - to be looped, soft circling ;
> Triggered - when creature appears, violent expanding/contracting
- When created the portal is using the Idle animation (looped)
  https://github.com/OpenDungeons/OpenDungeons/blob/development/source/rooms/RoomPortal.cpp#L80

The only thing I find wrong here is the use of the "Spawn" animation here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/rooms/RoomPortal.cpp#L132

which triggers the idle animation non-looped as a fallback. I guess the fix will be trivial. :)

**Comment by Bertram25** [comment] 2014-12-30 11:09
To move on with this issue, the only thing left to do is remove the ground tiles for portals.

**Comment by Bertram25** [comment] 2014-12-30 12:21
Ah btw, the issue isn't that trivial because rooms don't follow the shouldDisplayGroundTile() policy.

**Comment by Danimal696** [comment] 2014-12-30 12:39
what about using a dummy (empty) floor tile file?

**Comment by Bertram25** [comment] 2014-12-30 12:49
No, it's something we'll fix within the code, don't worry. :)

**Comment by hwoarangmy** [comment] 2014-12-30 12:58
No, it will be even worst to use an empty tile as floor tile because until now, room tiles are not colored (and thus, portal tiles would not be colored).
I've just seen that shouldDisplayGroundTile is not used anymore. Only in the renderer but because the clients are not notified for buildings, it will never be of use.
Instead, the logic has been to use shouldDisplayBuildingTile. If true, the building tile will be used. If false, the normal claimed tile will be. So, to easily handle this, we just have to override shouldDisplayBuildingTile for portals and make it return false. shouldDisplayGroundTile might be of use later when traps will be hidden and we will want to display only the trap (without ground tile) only when it has triggered once (but this has to be discussed as, AFAIK, no decision was made).

**Comment by Bertram25** [comment] 2014-12-30 13:18
> So, to easily handle this, we just have to override shouldDisplayBuildingTile for portals and make it return false.

Ok, cool. Seems I chose the wrong override, then. I'll test it.

> shouldDisplayGroundTile might be of use later when traps will be hidden and we will want to display only the trap (without ground tile) only when it has triggered once (but this has to be discussed as, AFAIK, no decision was made).

IMO, this is right way to use that, so if you need a decision, I say we can on with this as I can't see anything hurting in doing it that way. :)

**Comment by hwoarangmy** [comment] 2014-12-30 13:53
I've created #408 because we are getting too far from this issue (and I believe that this discussion will be interesting for later reference).

**Comment by Bertram25** [comment] 2014-12-30 14:07
Well done. We never know when we'll come back at all this.

**Closed as completed** 2014-12-30 21:28 UTC
Labels: Enhancement, Game content
