### ISSUE TITLE
Lava inhomogenity

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#716] opened 2015-05-03 10:57 UTC
Lava is inhomogeneous near the walls - all the lava is animated synchronously, but lava near walls is animated reverse. It doesn't look good at a screenshot, but very well seen at runtime.
![lava_inhomogenity](https://cloud.githubusercontent.com/assets/10726162/7444773/c3185cac-f193-11e4-9f43-79fd5e399116.png)

**Comment by hwoarangmy** [comment] 2015-05-03 20:12
Yes, that's a know problem since the tilesets. It comes from the tiles being rotated. Too many people are complaining, I guess we will have to do something ^^

**Comment by Bertram25** [comment] 2015-05-04 10:42
Indeed. Known and a duplicate of #694

**Closed as completed by Bertram25** 2015-05-04 10:42 UTC
Labels: Bug, Duplicate
