### ISSUE TITLE
Ideas for new traps

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1068] opened 2016-01-07 09:27 UTC
While reading #1067, I've been thinking we might want to also discuss ideas for new traps that we would like to implement in future versions. Let's keep the other issue focused to balancing, and throw in ideas here (that might be related or not to the balancing mechanisms we discuss in the other thread).

The offensive traps we currently have:
- Cannon
- Spike
- Boulder

**Comment by akien-mga** [comment] 2016-01-07 09:31
Now that we have more spells and creature skills, I've had the idea of a "mass silence" trap that would prevent any enemy creature from casting spells and/or using skills in a given area around the trap. It should likely be relatively limited in time, but could give a nice advantage in battle to the defending army.

Another simple idea could be an explosion trap that triggers an explosion spell in a given area - actually basically any spell could be turn into an offensive or defensive trap. I don't push for implementing exactly this yet, mostly throwing ideas to discuss :)

**Comment by akien-mga** [comment] 2016-01-07 09:35
When designing new traps, we should also keep in mind that traps almost always give an advantage to the defender in a dungeon aggression, as you can only build traps on claimed tiles, i.e. mostly in your own base. On the other hand adding more traps also means growing the skill tree, and forcing players to specialize themselves in only a subset of the available traps, so we can easily limit the risk of having overpowered dungeons with ten sorts of traps everywhere :)

**Comment by Danimal696** [comment] 2016-01-07 20:38
I had a few ideas, others we can "borrow" from DK:
Acid/Poison trap: it showers everything around (3-4 tiles) into a caustic/poisonous mist-> damage while the mist is active and creatures get poisoned/armor reduced after, i guess this could be split into two different traps.
Zapper: High magical damage at short range
Ice Totem: all surrounding creatures get slowed and Phys defense lowered (trap cant be attacked, its consumed after few shots)
Explosion mine: Phys damage, creatures are stunned a short time
Teleport trap: steeping on it teleports at ramdom anywhere on the map
Summon trap: a small horde of short lived creatures appears and bites at EVERYTHING

"Borrowed traps"
Fear trap: it checks against bravery and creatures that fail run away
Lava trap: the tile is turned into a lava tile
Alarm trap: creates "call to arms" over itself if a creature steps on it, even with sneaking/cloacked creatures
Fake magic box: its explodes and turns into a creature <- useless in any multiplayer game but good for campaign as a nasty surprise to player

Non traps ideas:
Auto-door: a door that only closes when ordered to or an enemy gets close
Wood/stone/metal barricade: block pass, destructible; stone and metal have properties like return-damage or damage-down when attacked
Outpost and its upgrade, Bunker: a single tile room, that gets an upgrade from the workshop, "Bunker", to allow creatures inside to attack and not recieve damage, when its destroyed it returns to being an outpost again.

**Comment by hwoarangmy** [comment] 2016-03-02 14:02
As @akien-mga said, the most easy would be to create a trap that can cast spells. That would allow to create many of the traps proposed in this thread (Zapper, Ice Totem, Explosion mine, Alarm trap).
It would also not be very hard to implement. However, it will require new models...

**Comment by hwoarangmy** [comment] 2016-03-02 14:29
Also note that "Teleport trap" and "Summon trap" should not be hard to implement, too.

Concerning "Lava trap", a creature that cannot walk over lava would not be able to move anymore and would require help from the keeper. However, it might not be a bad idea. But it would require some work and testing as it would change pathfinding (since creatres owned by a keepers with vision on it should not be allowed to go through).

@Danimal696  Concerning Outpost/Bunker, as I understand it, it would be a room where creatures stand and wait for enemies. If it is an outpost, should the creature be allowed to leave it to fight ?
Concerning the evolution, IIUC, it would work like traps. When the room is built, a workshop (if any) should start to work on it and produce a crafted entity that will be brought by a kobold to the room. Am I correct ? If so, it should not be too hard either. And that would open the way to rooms that need stuff from the workshop to be upgraded/functional (ie most advanced rooms)

**Comment by Danimal696** [comment] 2016-03-02 16:23
> @Danimal696 Concerning Outpost/Bunker, as I understand it, it would be a room where creatures stand and wait for enemies. If it is an outpost, should the creature be allowed to leave it to fight ?

Yes :) ; melee  creatures would rush to the enemy while ranged would stay there and take advantage of the protection from the bunker while ranged attacking.

> Concerning the evolution, IIUC, it would work like traps. When the room is built, a workshop (if any) should start to work on it and produce a crafted entity that will be brought by a kobold to the room. Am I correct ? If so, it should not be too hard either. And that would open the way to rooms that need stuff from the workshop to be upgraded/functional (ie most advanced rooms)

Exactly.

> Concerning "Lava trap", a creature that cannot walk over lava would not be able to move anymore and would require help from the keeper.

Why not creating a new auto-affliction? "In flames", when a creature is over a terrain it has 0 speed, it starts taking damage and get a speed boost to everything, repeat all turns until it manages to get out of the dangerous terrain (lava for almost all walkers and water for some creatures) or dies.

**Comment by Bertram25** [comment] 2016-03-30 22:25
@Loobinex For info.

Closing as duplicate of #1150

**Closed as completed by Bertram25** 2016-03-30 22:25 UTC
Labels: Duplicate, Enhancement, Game content
