### ISSUE TITLE
Simple Options/ Config hack 

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#374] opened 2014-12-13 12:31 UTC
Would you like to have an autostarting script which would contain in each line a command to be run in Console ? That way we could have customization compatible 1-1 with options from cmd line .... 
IT should be run after the GameMap reads the map from file ...

**Comment by Bertram25** [comment] 2014-12-13 14:30
From what I read, I suppose you're speaking of a file that is parsed after the level file to auto-execute commands?
IMHO, no. (But I'll let others speak as well).

What I'd rather have (but we're not yet there), is a script part in the level file that provide a way to (re)load a game state regarding AS. (which could trigger the equivalent to your feature question.) and permit to save the AS state when saving a game.
But before we work on that, there is a lot work on AS to first add proper script support.

What do you think guys?

**Comment by akien-mga** [comment] 2014-12-13 15:02
I've discussed this shortly on IRC with @tomluchowski, on from what I understood he wants some customisation config commands to be run at each game start:

> <paul424> I write list of console commands which ought to be run
> <paul424> at startup ...
> <paul424> like enableScrolling etc.

I don't see any command name "enableScrolling", but basically the idea behind this is user customisation of the interface. IMO, all this should be managed through a config file in ~/.config/opendungeons and in an "Options" menu, e.g.:
- Enable scrolling (tickbox)
- Scrolling speed (cursor)
- Mouse speed (cursor)
  etc.

Doing this through a startup script sounds a bit too much of a hack, I'm not sure it's worth spending time on it instead of doing a proper user settings manager.

**Comment by Bertram25** [comment] 2014-12-13 15:36
@akien-mga Thanks for taking the time to give more info. :)
If it's actually about configuring OD at a general level, then yes, I'd rather have a proper settings manager than a list of console commands executed at startup or equivalent.

That said, the main difference between the two is that the setting manager will read config options instead of console commands. The GUI part can even be done in a second step.

If this is true, I'll close this one as a duplicate of #3 but maybe @tomluchowski want to add more details first?

**Comment by tomluchowski** [comment] 2014-12-13 16:33
Shoudn't that be one langauge. Config language == console language ? 
Seems there is some obvious obstacle I don't see ... being ... ?

**Comment by hwoarangmy** [comment] 2014-12-13 22:01
IMHO, console should be used only for debugging. One of the reasons being that we might want to disable it for releases for example (even if I think it is not a good idea).

@tomluchowski could you tell us why do you really want this ?
If it is to allow to tune a level, AS should be used (even if it doesn't work for now).
If it is for general configuration, we should use some configuration manager (there is an issue for that, please feel free to take it if you want).
And if it is for debug purposes, we could add a console command to load a script (that would execute every command in the file like if they were console commands).

**Comment by Bertram25** [comment] 2014-12-30 11:00
Closing the issue as it seems a duplicate of the options gui menu, and this seems more a hack than anything else.
For the record, it was decided that AS will be used mostly for in game scripting and much less for console commands if we can avoid it.
We'll probably add some command to call an AS function but that's a later story.

**Closed as completed by Bertram25** 2014-12-30 11:00 UTC
Labels: Enhancement, Invalid, Discussion
