### ISSUE TITLE
Logo Enhancement

### ISSUE THREAD

**Issue by Wout-van-Dongen** [OpenDungeons/OpenDungeons#1028] opened 2015-11-28 16:03 UTC
I've been working on some ideas to enhance the OD representation.
Feedback is appreciated ;o
![opendungeons_title_copper](https://cloud.githubusercontent.com/assets/6794691/11452702/b6b4ae72-95f1-11e5-9c62-c9f09f710c7c.png)

**Comment by hwoarangmy** [comment] 2015-12-02 09:31
This logo is nice. However, it might be a little be too "serious" IMHO. What I liked the most in the original DK (and I hope we will successfully keep in OD) is the humor. And from this point of view, the current logo is closer to what I would expect for such a game.

Note that it is only my opinion and if the others want to replace the current one, I won't be against.

**Comment by Bertram25** [comment] 2016-03-30 21:05
Closing as duplicate of #1052

**Closed as completed by Bertram25** 2016-03-30 21:05 UTC
Labels: Enhancement, Game content
