### ISSUE TITLE
Segfault during gameplay

### ISSUE THREAD

**Issue by lowerthanred** [OpenDungeons/OpenDungeons#610] opened 2015-04-01 23:43 UTC
A segfault occurred during gameplay on map The Bridge, possibly connected to many creatures being onscreen.
Backtrace:

```
Computing turn 2161
SERVER - Removing Creature Goblin89
During this turn there were 13 calls to GameMap::path().miscUpkeepTime=4676
Server sends newturn=2161
Client received turnStarted=2161
CLIENT - Removing Creature Goblin89
signal 11 (Segmentation fault), address is 0 from 0x7f5cb6d96980

[bt]: (1) /usr/lib/nvidia-331/libnvidia-glcore.so.331.113 : +0x15a5980 [0x7f5cb6d96980]
[bt]: (2) /usr/lib/nvidia-331/libnvidia-glcore.so.331.113 : +0x15a5980 [0x7f5cb6d96980]
[bt]: (3) /usr/lib/nvidia-331/libnvidia-glcore.so.331.113 : +0x16be5b8 [0x7f5cb6eaf5b8]
[bt]: (4) /usr/lib/nvidia-331/libnvidia-glcore.so.331.113 : +0x16bee68 [0x7f5cb6eafe68]
[bt]: (5) /usr/lib/nvidia-331/libnvidia-glcore.so.331.113 : +0x130d2c2 [0x7f5cb6afe2c2]
[bt]: (6) lib/RenderSystem_GL.so.1.9.0 : Ogre::GLRenderSystem::_render(Ogre::RenderOperation const&)+0x4f6 [0x7f5cbe731526]
[bt]: (7) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::SceneManager::renderSingleObject(Ogre::Renderable*, Ogre::Pass const*, bool, bool, Ogre::HashedVector<Ogre::Light*> const*)+0xd02 [0x7f5ccd990fe2]
[bt]: (8) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::QueuedRenderableCollection::acceptVisitorGrouped(Ogre::QueuedRenderableVisitor*) const+0x69 [0x7f5ccd942769]
[bt]: (9) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::QueuedRenderableCollection::acceptVisitor(Ogre::QueuedRenderableVisitor*, Ogre::QueuedRenderableCollection::OrganisationMode) const+0x1b [0x7f5ccd94282b]
[bt]: (10) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::SceneManager::renderBasicQueueGroupObjects(Ogre::RenderQueueGroup*, Ogre::QueuedRenderableCollection::OrganisationMode)+0x62 [0x7f5ccd97d942]
[bt]: (11) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::SceneManager::renderVisibleObjectsDefaultSequence()+0x9c [0x7f5ccd97cb2c]
[bt]: (12) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::SceneManager::_renderScene(Ogre::Camera*, Ogre::Viewport*, bool)+0x516 [0x7f5ccd98ffe6]
[bt]: (13) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::Camera::_renderScene(Ogre::Viewport*, bool)+0x16b [0x7f5ccd780a3b]
[bt]: (14) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::RenderTarget::_updateViewport(Ogre::Viewport*, bool)+0x1e [0x7f5ccd810c1e]
[bt]: (15) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::RenderTarget::_updateAutoUpdatedViewports(bool)+0x5b [0x7f5ccd810bdb]
[bt]: (16) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::RenderTarget::updateImpl()+0x1e [0x7f5ccd81078e]
[bt]: (17) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::RenderTarget::update(bool)+0x14 [0x7f5ccd810d84]
[bt]: (18) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::RenderSystem::_updateAllRenderTargets(bool)+0x5f [0x7f5ccd84641f]
[bt]: (19) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::Root::_updateAllRenderTargets()+0x1a [0x7f5ccd7e067a]
[bt]: (20) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::Root::renderOneFrame()+0x20 [0x7f5ccd7e0730]
[bt]: (21) /home/pkj1/opendungeons/OpenDungeons-git20150329-Linux64/lib/libOgreMain.so.1.9.0 : Ogre::Root::startRendering()+0x2d [0x7f5ccd7e076d]
[bt]: (22) ./opendungeons.x86_64 : ODApplication::ODApplication()+0x5fe [0x5c99ae]
[bt]: (23) ./opendungeons.x86_64 : main+0x48 [0x45cea8]
[bt]: (24) /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main+0xf5 [0x7f5cca248ec5]
[bt]: (25) ./opendungeons.x86_64() [0x45cfaf]
```

**Comment by lowerthanred** [comment] 2015-04-02 00:17
opendungeons.log: http://www.pasteall.org/57619

**Comment by hwoarangmy** [comment] 2015-04-02 07:18
Thanks for the feedback. You should also have a replay in your replay folder. Do you have it ? It would help much.
Moreover, the segfault seems to occur in rendering phase. Could you please try the replay so that we know if it is reproducible with it ?

**Comment by hwoarangmy** [comment] 2015-04-02 21:35
I've seen nothing suspect in the log. Moreover, the backtrace suggests that the problem comes from rendering (the segfault happens in Ogre rendering code, not in OD). Could you please try the replay and tell us if it reproduces the crash ?

**Comment by lowerthanred** [comment] 2015-04-03 01:18
The replay plays out ok until the last turn before the segfault in the original game; after that point, terminal output stops, while units continue walking to where they were headed before, and then just stand there idly.
The segfault reproduces after pressing ESC and confirming, and the same backtrace is produced. But it seems that if the camera is positioned so that no units are in view while this is done, nothing bad happens and I land on the main menu.
The ODR file: http://www.mediafire.com/download/7emh6kwo3amnl13/replay_20150401_191455.odr

**Comment by hwoarangmy** [comment] 2015-04-03 07:51
That's very interesting, thanks for the investigation. I will try to reproduce ASAP. I've tried to google a bit your stacktrace and I've seen people telling that the bug were in the drivers. They fixed it by upgrading it. Not sure it is the case here.
Anyway, can you confirm the bug is systematic when you quit the game at the end of the replay with creatures on screen ?
Moreover, is it something specific to this replay or do you have a systematic segfault when you quit any game ?

BTW, having the replay with creatures going to their last destination and standing idly is the expected behaviour.

**Comment by hwoarangmy** [comment] 2015-04-03 19:58
I've had a similar segfault as you had. I am currently having a look if I can see something

**Comment by hwoarangmy** [comment] 2015-04-03 21:28
@lowerthanred Thanks for your replay I get a systematic segfault when CaveHornet37 is removed after only a few minutes (I just launch your replay, I do nothing more - no camera move or whatever).

@akien-mga @Bertram25 @oyvindln Could you please confirm if you can also reproduce the segfault ?

The good thing is that since it is systematic, it should not be too hard to find out which commit introduced that (even if it may be time consuming)

**Comment by lowerthanred** [comment] 2015-04-03 21:46
Github swallowed my comment - the crash is indeed systematic under these conditions, and I get a similar one now and then mid-gameplay, but there is no general problem with exiting.

**Comment by Bertram25** [comment] 2015-04-03 21:53
Testing once downloaded (in a few minutes).

**Comment by Bertram25** [comment] 2015-04-03 21:56
It's fun to see someone else playing a bit. :D I may learn a few things... :>

**Comment by Bertram25** [comment] 2015-04-03 22:24
No crash on my own. I was using hwoarangmy's latest PR about waveportals binary, linux version.
The creatures stop doing stuff at turn 2161. I've then waited for something like 10 minutes but no crash.

**Comment by akien-mga** [comment] 2015-04-04 08:13
I'll try it here, I have both a intel GPU and a nvidia GPU (using the nvidia 346.47 driver, so not the same one, but let's see).

**Comment by akien-mga** [comment] 2015-04-04 10:09
Watching the replay, I think this level needs some small patches of gold on the sides to make it worth expanding your dungeon laterally. Currently there are too little possible strategies IMO (rush to the middle and the big gold resources or harvest the big patch behind your dungeon). The small patches should not be enough to sustain a dungeon though, but it could help getting started with the library, etc.

**Comment by akien-mga** [comment] 2015-04-04 10:11
Other note to self: the help text should probably introduce the "active spot" concept and why it's more efficient to build 3x3, 3x5 or 5x5 than e.g. 4x6.

**Comment by akien-mga** [comment] 2015-04-04 10:17
> Watching the replay, I think this level needs some small patches of gold on the sides to make it worth expanding your dungeon laterally. 

Actually watching further, it looks like gold is absolutely not an issue ;-) So if we were to add some patches of gold to the sides of the dungeon, we should also remove part of the huge gold resources in the middle and the top/bottom.

**Comment by akien-mga** [comment] 2015-04-04 10:29
So, no crash for me using my Intel GPU on Linux with the open source drivers. Will try nvidia now.

**Comment by akien-mga** [comment] 2015-04-04 11:01
No segfault either with nvidia 346.47 on Linux 64bit.

So the issue might be in nvidia 331.113. It's the most recent version in the 331 branch though (at least supposing that Ubuntu does a good QA job).

**Comment by akien-mga** [comment] 2015-04-04 11:03
Note that I tested using the git20150329 binary release, since I supposed @lowerthanred was using this binary when experiencing the segfault.

**Comment by hwoarangmy** [comment] 2015-04-04 11:29
I've made some tries. The bug seems not rare enough to be old or I would have seen it. From what I've seen in the latest PR, I would guess that the bug comes from our recent changes on materials. I will try to see if I reproduce with older materials.

@akien-mga @Bertram25 Thanks for the tests.

**Comment by akien-mga** [comment] 2015-04-04 13:27
Tried again with @Bertram25's branch, no segfault either when going all the way to turn 2161.

**Comment by Bertram25** [comment] 2015-04-04 16:29
@akien-mga Feel free to change the bridge level if you want. I must say I wantes to make it more twisted anyway.

**Comment by hwoarangmy** [comment] 2015-04-04 16:35
I've also tried @Bertram25 branch and I get the same segfault. I've tried to change randomly the cavehornet materials to see if I could find out what causes the crash. Strangely, if I rename cavehornet.png as cavehornet2.png and change the 2 material files, I don't get the segfault. That might sound strange but it is systematic. If I return to the older name, it segfaults again...

**Comment by Bertram25** [comment] 2015-04-04 17:13
Then I'd say do it and let's comment the material about that crash so that we don't revert accidentally later if we can't find why. Is the cavehornet png file use elsewhere in OD or in the Ogre Sdk?

**Comment by hwoarangmy** [comment] 2015-04-04 19:37
> Is the cavehornet png file use elsewhere in OD or in the Ogre Sdk?

AFAIK, no. It used to be Cavehornet_col.png. But I've tried to use different names (like cavehornet2.png and I get the same behaviour).

> Then I'd say do it and let's comment the material about that crash

Unfortunately, I don't think it will be that easy. First, if we have a problem with cavehornet (in my case), we can assume there might be similar problems with other creatures. Moreover, if I compare my log with @lowerthanred, I see that my crash (with a backtrace very similar to his) happens after a cavehornet is removed. But in his case, it happens after a goblin is removed (no cavehornet is removed in this turn). So, we can assume that at least the goblin and the cavehornet have this kind of problem.
I will make a level with many cavehornet getting killed to see if I can easily reproduce the crash with this similar backtrace because the one I get when playing the replay is not exactly the same.

**Comment by akien-mga** [comment] 2015-04-04 19:58
I'm not sure I understand. Why would the crash be linked to the renaming of the texture? If the texture name is wrong, the material file should throw an error when it's parsed, no?

**Comment by hwoarangmy** [comment] 2015-04-04 20:08
I never said the texture name is wrong. I just say that when I rename it (and change the name in the corresponding materials), I get no segfault. That's just an observation, not an explication.

**Comment by akien-mga** [comment] 2015-04-04 20:21
> I never said the texture name is wrong. I just say that when I rename it (and change the name in the corresponding materials), I get no segfault. That's just an observation, not an explication.

Thanks for the clarification :-) That's definitely an interesting symptom :-)

**Comment by hwoarangmy** [comment] 2015-04-04 20:42
After googling a bit, the few issues I've seen with similar backtrace that got an explication said that the problem comes from a bug in the driver that is fixed when upgrading them. I'm currently downloading the latest ones for my computer. I will tell if it changes something.

**Comment by Bertram25** [comment] 2015-04-04 21:12
K, definitely curious, but this might definitely come from the way the shaders are interpreted and the texture is cached and uploaded. Very interesting while somewhat nasty.

**Comment by hwoarangmy** [comment] 2015-04-04 22:27
I've upgraded my drivers and got no segfault since then. Just like the original backtrace, my segfault was in the drivers so we can assume the bug is more or less the same (even if I use windows).
For the record, my drivers were pretty old (04/03/2012 version: 8.17.12.9616).
@lowerthanred Could you please try to upgrade your drivers and check if you still have the segfault ?

**Comment by Bertram25** [comment] 2015-04-04 23:02
Ah. I must say I'm a bit reassured. :)

**Comment by akien-mga** [comment] 2015-04-05 08:24
> Ah. I must say I'm a bit reassured. :)

For me it's the contrary, I'm a bit concerned. Because the nvidia driver version 331.113 used by @lowerthanred is the one provided by Ubuntu AFAICT: http://packages.ubuntu.com/search?keywords=nvidia&searchon=names&suite=trusty&section=all (at least on 14.04 LTS and 14.10).

Only Ubuntu 15.04 has the current legacy GPU longterm branch (340.x) and the new longterm branch (346.x), see the currently supported drivers here: http://www.nvidia.com/object/unix.html

So once again Ubuntu is lagging behind, and normally we shouldn't have to care about supported outdated drivers... Now, most Linux users are sadly on Ubuntu or a Ubuntu-based distro, so if we have such kind of segfaults in 0.5.0 it will still be pretty bad for us :-/

So if there's a way to temporarily workaround the issue, we should go for it IMO. We can also state in the release notes that unsupported drivers are... unsupported, and that Ubuntu users should file bug reports at Ubuntu to ask for an official driver update in the LTS branch.

**Comment by hwoarangmy** [comment] 2015-04-05 09:14
@akien-mga You raised a valid point. But the only solution I can see is to revert what @Danimal696 did on normals since I guess that's what causes the crash...

**Comment by Bertram25** [comment] 2015-04-05 09:29
This could also some ogre bug nvidia workarounded themselves. I guess I'll google a bit, who knows...

**Comment by hwoarangmy** [comment] 2015-04-05 13:22
For the record, if you find something, I get the following bt:

```
0  0x14066183 in nvoglv32!DrvPresentBuffers () from C:\Windows\SysWOW64\nvoglv32.dll
1  0x14138ed2 in nvoglv32!DrvPresentBuffers () from C:\Windows\SysWOW64\nvoglv32.dll
2  0x1413ae42 in nvoglv32!DrvPresentBuffers () from C:\Windows\SysWOW64\nvoglv32.dll
3  0x1413b2c3 in nvoglv32!DrvPresentBuffers () from C:\Windows\SysWOW64\nvoglv32.dll
4  0x1394376c in ?? () from C:\Windows\SysWOW64\nvoglv32.dll
5  0x12aabdea in Ogre::GLRenderSystem::_render (this=0x11d38758, op=...) at ..\..\..\..\RenderSystems\GL\src\OgreGLRenderSystem.cpp:2964
6  0x03ecbe41 in Ogre::SceneManager::renderSingleObject (this=0x11dbc6d0, rend=0x11e09530, pass=0x11d57d10, lightScissoringClipping=true, doLightIteration=true, manualLightList=0x0) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:3483
7  0x03eca53d in Ogre::SceneManager::SceneMgrQueuedRenderableVisitor::visit (this=0x11dc0b8c, r=0x11e09530) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:2910
8  0x03e906bf in Ogre::QueuedRenderableCollection::acceptVisitorGrouped (this=0x1e644538, visitor=0x11dc0b8c) at ..\..\..\OgreMain\src\OgreRenderQueueSortingGrouping.cpp:450
9  0x03e90524 in Ogre::QueuedRenderableCollection::acceptVisitor (this=0x1e644538, visitor=0x11dc0b8c, om=Ogre::QueuedRenderableCollection::OM_PASS_GROUP) at ..\..\..\OgreMain\src\OgreRenderQueueSortingGrouping.cpp:418
10 0x03eca96a in Ogre::SceneManager::renderObjects (this=0x11dbc6d0, objs=..., om=Ogre::QueuedRenderableCollection::OM_PASS_GROUP, lightScissoringClipping=true, doLightIteration=true, manualLightList=0x0) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:3011
11 0x03ecac47 in Ogre::SceneManager::renderBasicQueueGroupObjects (this=0x11dbc6d0, pGroup=0x11f43e80, om=Ogre::QueuedRenderableCollection::OM_PASS_GROUP) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:3089
12 0x03ecabb6 in Ogre::SceneManager::_renderQueueGroupObjects (this=0x11dbc6d0, pGroup=0x11f43e80, om=Ogre::QueuedRenderableCollection::OM_PASS_GROUP) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:3068
13 0x03ec86bc in Ogre::SceneManager::renderVisibleObjectsDefaultSequence (this=0x11dbc6d0) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:2348
14 0x03ec845c in Ogre::SceneManager::_renderVisibleObjects (this=0x11dbc6d0) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:2264
15 0x03ec4cd4 in Ogre::SceneManager::_renderScene (this=0x11dbc6d0, camera=0x11d714b0, vp=0x12833560, includeOverlays=true) at ..\..\..\OgreMain\src\OgreSceneManager.cpp:1561
16 0x03d8ac1e in Ogre::Camera::_renderScene (this=0x11d714b0, vp=0x12833560, includeOverlays=true) at ..\..\..\OgreMain\src\OgreCamera.cpp:427
17 0x03f5e002 in Ogre::Viewport::update (this=0x12833560) at ..\..\..\OgreMain\src\OgreViewport.cpp:224
18 0x03ea32f3 in Ogre::RenderTarget::_updateViewport (this=0x11d3d3a8, viewport=0x12833560, updateStatistics=true) at ..\..\..\OgreMain\src\OgreRenderTarget.cpp:200
19 0x03ea3229 in Ogre::RenderTarget::_updateAutoUpdatedViewports (this=0x11d3d3a8, updateStatistics=true) at ..\..\..\OgreMain\src\OgreRenderTarget.cpp:178
20 0x03ea317e in Ogre::RenderTarget::updateImpl (this=0x11d3d3a8) at ..\..\..\OgreMain\src\OgreRenderTarget.cpp:155
21 0x03ea4b58 in Ogre::RenderTarget::update (this=0x11d3d3a8, swap=false) at ..\..\..\OgreMain\src\OgreRenderTarget.cpp:613
22 0x03e913c3 in Ogre::RenderSystem::_updateAllRenderTargets (this=0x11d38758, swapBuffers=false) at ..\..\..\OgreMain\src\OgreRenderSystem.cpp:126
23 0x03ebcf9d in Ogre::Root::_updateAllRenderTargets (this=0x28f8b0) at ..\..\..\OgreMain\src\OgreRoot.cpp:1410
24 0x03ebafdd in Ogre::Root::renderOneFrame (this=0x28f8b0) at ..\..\..\OgreMain\src\OgreRoot.cpp:983
25 0x03ebaf98 in Ogre::Root::startRendering (this=0x28f8b0) at ..\..\..\OgreMain\src\OgreRoot.cpp:973
26 0x0051a8c9 in _fu424___ZN4Ogre11ColourValue5WhiteE () at C:\devMinGW\od-gh-src\source\ODApplication.cpp:134
27 0x0051af89 in WinMain@16 (hInst=0x400000, strCmdLine=strCmdLine@entry=0x3c7565d "") at C:\devMinGW\od-gh-src\source\main.cpp:66
28 0x005b829b in main (argc=1, argv=0x3eca0, __p__environ=0x31f10) at ../mingwrt-4.0.3-1-mingw32-src/src/libcrt/crt/main.c:91
```

**Comment by Bertram25** [comment] 2015-04-06 17:12
Well, this could be anything among those, for instance:
https://ogre3d.atlassian.net/browse/OGRE-85?jql=text%20~%20%22nvidia%22
http://us.download.nvidia.com/Windows/331.65/331.65-winxp-desktop-release-notes.pdf
http://us.download.nvidia.com/Windows/347.88/347.88-win8-win7-winvista-desktop-release-notes.pdf

I've spent some time searching for something in the above links + similar, but no luck so far. :S I tried looking also at the RTSS bugs but nothing relevant either.
Do you think it is possible to rather easily update the drivers on Ubuntu for instance? i f we can't, then maybe disabling the RTSS for users with such a problem could be a workaround? (but this means redoing normal-less materials for every models first and add support for the option).

In any case IMHO, we should warn about that nvidia drivers problem but i can't see any easy way to get rid of this crash. Do you think we can proceed without fixing that one for 0.5.0?

**Comment by akien-mga** [comment] 2015-04-06 18:32
> In any case IMHO, we should warn about that nvidia drivers problem but i can't see any easy way to get rid of this crash. Do you think we can proceed without fixing that one for 0.5.0?

I think a mention in the README and the release notes will do. 0.5.0 will still be an alpha/beta game, so we don't necessarily aim for a perfect support of every hardware and drivers. Since the bug is fixed in currently-supported drivers, let's just tell our Ubuntu players to have a go at upgrading their drivers, it's not too hard and I'm pretty sure Ubuntu has some good doc about it.

**Comment by Bertram25** [comment] 2015-04-06 19:41
K. But then, are we going to fix this at all?

**Comment by hwoarangmy** [comment] 2015-04-08 08:22
So, do we close this as won't fix ?

**Comment by akien-mga** [comment] 2015-04-08 08:29
IMO yes. If this was for a major release, with the game almost feature complete and well-balanced, I would push for a workaround to reach as many players as possible. But now we're just past the tech preview that 0.4.9 was, and we are entering a kind of beta level I'd say. So let's not bother too much about outdated drivers (even though it's a concern that Ubuntu 14.04 LTS has outdated drivers, but with luck they'll update them soon to the currently long-term support branch from nvidia).

**Closed as completed** 2015-04-08 08:29 UTC
Labels: Bug, Won't fix

**Comment by Bertram25** [comment] 2015-04-08 08:38
+1 Let's move on. :)
