### ISSUE TITLE
Opt-in parameter to link against system FreeMono.ttf font

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#366] opened 2014-12-07 11:05 UTC
**Edit:** This was fixed by dropping FreeMono.ttf

As discussed in https://github.com/OpenDungeons/OpenDungeons/pull/362#issuecomment-65931864 and onward.

Basically the idea would be to let packagers define the absolute path to the system directory containing the FreeMono.ttf (and could be extended to any new "common" font that we would like to use in the future).

Unless I'm mistaken, the font is currently addressed by https://github.com/OpenDungeons/OpenDungeons/blob/development/gui/ogrefonts.fontdef#L4 which searches in the path defined for the GUI resource here: https://github.com/OpenDungeons/OpenDungeons/blob/development/cmake/config/resources.cfg.in#L10-L12

In system-wide installations, the font can be safely removed from the gui/ folder (at least based on my early tests) if the **relative** path to the font directory is given, i.e.:
`FileSystem=../../fonts/gnu-free` on Mageia
`FileSystem=../../fonts/freetype` on Debian

Now, using a relative path for this is a bit difficult to achieve with a CMake parameter IMO (if it were e.g. `GNU_FREEFONT_PATH=/usr/share/fonts/gnu-free`).

So I would need some input from our OGRE resource gurus (@Bertram25, @hwoarangmy) to know how to specify an absolute path in the resources.cfg file.
Actually I'll open another issue for that because the resources.cfg.in file needs some love IMO (it was designed to be configured through CMake but actually there is no need to do so with @Bertram25's implementation of system-wide data paths).

**Comment by akien-mga** [comment] 2014-12-07 19:36
I've asked Mageia developers about this, and I was told that project such as ours should probably use fontconfig for this purpose: http://www.freedesktop.org/wiki/Software/fontconfig/

**Comment by oyvindln** [comment] 2014-12-09 00:43
When it comes to the FreeMono font, it's used by the ogre text rendering, which I'm not sure we are going to use in the future. Right now it's used for chat, console and text following the pointer, and I think all of these could be replaced by the GUI framework (CEGUI) eventually, though that is something we have to discuss. (I'm working on the console part, but I haven't been able to get much done on that since the pull request for health reasons.)

The issue is still there as CEGUI also uses a font that is currently bundled, but I am not sure how CEGUI looks up resources.

**Comment by Bertram25** [comment] 2014-12-09 16:48
@oyvindln I hope you're going better, btw. Or at least, that you are taking care of yourself. :)

> The issue is still there as CEGUI also uses a font that is currently bundled, but I am not sure how CEGUI looks up resources.

CEGUI is using the Ogre as a resource manager. See here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/render/Gui.cpp#L66

So, IMHO, if we can solve the problem for Ogre, we'll solve it for CEGUI.

Btw, the simplest way to add a system font I could find is to add a resource location in the code:
http://www.ogre3d.org/addonforums/viewtopic.php?p=71488&sid=3a5161b9e8c1fe90749111687ad2aec4#p71488

Otherwise, we might need to code our own custom resource manager and override the way it is looking for font files. We may even have to load font as raw streams AFAIK.

SO, IMHO, if we can add a simple way to tell the resource manager to look for the linux system font path, and call the font as usual, it should d o the trick.
Not sure we should do that for 0.4.9, though.

**Comment by akien-mga** [comment] 2014-12-09 16:58
Set the milestone to Later for now, it's not a high priority enhancement for 0.4.9.

Basically the link you gave on the Ogre forum seems to be the in-code equivalent of what I proposed above for the resources.cfg file:

> In system-wide installations, the font can be safely removed from the gui/ folder (at least based on my early tests) if the relative path to the font directory is given, i.e.:
> `FileSystem=../../fonts/gnu-free` on Mageia
> `FileSystem=../../fonts/freetype` on Debian
> (Note that I tested the above on Mageia and it does work fine)

The main issue with this being the use of a relative path, when we would like something like:
`FileSystem=@SYSTEM_FREEFONT_PATH@` where SYSTEM_FREEFONT_PATH would be passed as a CMake argument.

But currently Ogre would interpret the FileSystem as `${OD_DATA_DIR}/${SYSTEM_FREEFONT_PATH}`, and that's not what we want.

**Comment by Bertram25** [comment] 2014-12-09 18:12
> But currently Ogre would interpret the FileSystem as ${OD_DATA_DIR}/${SYSTEM_FREEFONT_PATH}, and that's not what we want.

Dang. Then, I guess we're good to add a custom resource loader for such stuff. I will simply say that Ogre team has weird ways to handle stuff sometimes, even they've got one of the best open sourced 3d engine out there.

Do you think this would be acceptable to use such (weird) relative paths for fonts until we've sorted this out? Or is it a bit too early?

**Comment by akien-mga** [comment] 2014-12-09 18:16
> Do you think this would be acceptable to use such (weird) relative paths for fonts until we've sorted this out? Or is it a bit too early?

Sure, for now I can patch resources.cfg to add the relative path. This is really low priority, there is no real problem with bundling open source fonts. Packagers are used to this kind of stuff (and most of the time don't really care about it ;-) ).

There's no hurry for this issue.

**Comment by Bertram25** [comment] 2014-12-09 18:20
k, but it's a real blunder Ogre doesn't handle special external resources. I may open a thread about this to see if they are more open to add this back in Ogre 2.0.

**Comment by oyvindln** [comment] 2014-12-09 18:23
Are you sure it doesn't?

**Comment by Bertram25** [comment] 2014-12-09 18:34
> Are you sure it doesn't?

From all I could read, it doesn't accept '/usr/...' as a resource path. But if you find something that proves me wrong, I'm all ok for it. :)

**Comment by akien-mga** [comment] 2014-12-09 19:39
> > Are you sure it doesn't?
> 
> From all I could read, it doesn't accept '/usr/...' as a resource path. But if you find something that proves me wrong, I'm all ok for it. :)

My initial guess that we could be the ones forcing the OD_DATA_PATH as a prefix for the Ogre resource manager. At least that's the current resources.cfg.in file suggests with:

`FileSystem = @OPENDUNGEONS_MEDIA_DIR@/gui`

Before @Bertram25 implemented the OD_DATA_DIR and I wrote the Linux install instructions, the method planned for system wide installation was a system resources_install.cfg in which the @OPENDUNGEONS_MEDIA_DIR@ would be hardcoded, so supposedly it was expected that absolute paths would be working.

Now we are using relative paths in resources.cfg, showing that OD_DATA_PATH is taken as current directory (which is great) but might be the cause for not respecting absolute path.

**Comment by Bertram25** [comment] 2014-12-30 11:03
> Now we are using relative paths in resources.cfg, showing that OD_DATA_PATH is taken as current directory (which is great) but might be the cause for not respecting absolute path.

If both you and @oyvindln are right, then there is a funny behaviour regression here. I'll have a look sooner or later.

**Comment by Bertram25** [comment] 2015-02-02 20:49
With latest changes (the use of CEGUI for the console, AFAIK, the game runs fine without FreeMono.ttf).

**Comment by Bertram25** [comment] 2015-02-02 21:00
Ok, in case we may need an absolute resource path, I tested by adding this:

``` c++
Ogre::ResourceGroupManager::getSingleton().addResourceLocation("/usr/share/fonts/truetype/freefont", "FileSystem", "Graphics");
```

The log output is this:

```
Added resource location '/usr/share/fonts/truetype/freefont' of type 'FileSystem' to resource group 'Graphics'
```

So this is doing fine. I think this issue can be closed, though.

@akien-mga WDYT?

EDIT: We could also remove the FreeMono.ttf file, right?

**Comment by oyvindln** [comment] 2015-02-02 21:24
I we're still use another font file (MedievalSharp_bold.ttf) for the chat, stats display etc, so I don't know the cegui console solves the issue. We might want to use CEGUI for that too at some point but for now we aren't.  (Though we can probably remove that file yes.)

**Comment by Bertram25** [comment] 2015-02-02 21:39
True. This will be needed one day, but I suppose it's another issue.
What I'd add first is using another color for the commands output. It should give something cool. :)
If everyone agrees, let's say removing this font and the corresponding possible links to it will be enough to close this issue.
Then, once we'll need another font for the console and so on, we can open a separate one.

WDYT?

**Closed as completed** 2015-02-11 23:07 UTC
Labels: Enhancement, Linux
