### ISSUE TITLE
Editor: minimap coordinates are not reset when loading a new level

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#478] opened 2015-02-04 11:23 UTC
If you load a level in the editor, move the camera to get the minimap centered on another pair of coordinates than the start point, close the level and load a new one, the minimap will show the part of the level where you were previously (and if you loaded a different level, it will show the coordinates in this new level that correspond to where you were in the first level).

Move the camera does refresh the minimap though, so it's not a big issue.
I've tested the skirmish mode and it seems that the minimap does get refreshed there.

Example: Scream in the Dark: the minimap shows the location of Scream in the Dark that corresponds to where I was previously when editing Greed or Might.
![od-sitd](https://cloud.githubusercontent.com/assets/4701338/6039566/8d51be8a-ac68-11e4-936d-b6e0c623622a.jpg)

**Comment by Bertram25** [comment] 2015-02-16 10:31
This is due to the fact the minimap is updated only when moving (on the editor mode) now because of one of my commits. The bug doesn't happen on the game mode since the minimap is also updated at least once per turn and at the first turn.

I guess a minimap refresher should simply be called on the editor mode activation. But please, do not make the minimap always update again as it is performance heavy.

Btw, setting milestone to 0.5.0 as it is a regression.

**Comment by oyvindln** [comment] 2015-02-16 15:04
It looks to me like it's redrawn every frame: https://github.com/OpenDungeons/OpenDungeons/blob/development/source/modes/EditorMode.cpp#L811

**Comment by Bertram25** [comment] 2015-02-16 15:10
True, and a nice catch, but I was speaking of the camera position info:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/camera/CameraManager.cpp#L223
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/camera/CameraManager.cpp#L228
Maybe it's also possible to not update/redraw the pixelbox when not moving the camera and do no actions on tiles?

**Comment by oyvindln** [comment] 2015-02-16 15:20
It's the draw call that takes up a lot of time, and not the camera update, but yeah, we should look into only doing minimap updates when needed. I have fixed the coordinate issue on my local branch, so I will try to get a PR up soon.

**Comment by Bertram25** [comment] 2015-02-18 11:12
This is fixed with https://github.com/OpenDungeons/OpenDungeons/commit/600a41495b16311e1835a720ea47401616891e62

**Closed as completed by Bertram25** 2015-02-18 11:12 UTC
Labels: Bug, Map Editor
