### ISSUE TITLE
Claimed wall textures are much too big

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#810] opened 2015-06-16 11:39 UTC
The consequence is that when the first wall is claimed (and the mesh loaded), the game freezes.

Seems like I was too fast to integrate #808 

@Danimal696 Could you please reduce a bit its size ? 2048x2048 is too much...

I'm pretty sure that 512x512 would be enough. I also bet that's a reason why the game freezes when we build a room (because of loading textures for ground tiles as well as the building objects).

**Comment by akien-mga** [comment] 2015-06-16 12:08
Note that the 2048x2048 version could go in the -media-source repo, while we use a lower res version in the game.

**Comment by Danimal696** [comment] 2015-06-16 15:36
1024 will the least we can afford if we want them to have some quality, have in mind theres a lot of them packed into the same png

**Comment by Danimal696** [comment] 2015-06-16 16:00
please try now, on my pc both worked perfectly

**Comment by hwoarangmy** [comment] 2015-06-16 17:05
ok. On my way

**Comment by hwoarangmy** [comment] 2015-06-16 17:21
I've tried. It is faster but you also need to resize ClaimedWallMask.png and ClaimedWallNormal.png.
However, I still have a small lag just when the tile is claimed (and my computer is decent: i7 with GeForge GTX 560M).
I've tried with 512x512 pngs and got no lag but the quality is clearly lower.

**Comment by akien-mga** [comment] 2015-06-16 17:39
Could we split those textures into several files? I guess the issue is that the file itself is too big, and several 512x512 files might help circumvent this hardware issue.

**Comment by Danimal696** [comment] 2015-06-16 19:25
> Could we split those textures into several files?

When i did this one i wanted to avoid exactly that, it would help when adding diferent biomes to be into the same file, but im going to just cut them all.

> I still have a small lag just when the tile is claimed (and my computer is decent: i7 with GeForge GTX 560M).

I have a I5 and AMD Radeon HD 7700 and see no lag at all, nvidia drivers migth be the culprit in your case

**Comment by hwoarangmy** [comment] 2015-06-16 20:03
> I have a I5 and AMD Radeon HD 7700 and see no lag at all, nvidia drivers migth be the culprit in your case

Well, the main reason is that I use a debug version which is much slower. However, its pretty nice to see the bottlenecks and the problems that may happen on weaker configurations

**Comment by Danimal696** [comment] 2015-06-17 12:22
This is very important, are claimed walls harcoded to only use Claimedwall.material?
no matter what i change on the model or material it always uses whats in Claimedwall.material, and its making impossible to make the tiles piece by piece

**Comment by Danimal696** [comment] 2015-06-17 12:28
more on that, its harcoded on the tileset config file, but now im needing 3 textures = 3 material per wall tile model, tileset config only allows 1 material. ill try merging textures with different sizes

**Comment by akien-mga** [comment] 2015-06-17 12:38
Why 3 textures = 3 materials? You can declare several textures in the same material script no?

**Comment by Danimal696** [comment] 2015-06-17 12:57
how? give me an example, the main problem is how that is done inside blender so uv map doesnt overlap all textures?

**Comment by Danimal696** [comment] 2015-06-17 15:01
``` lua
// DCW0101 genrated by blender2ogre 0.6.0

material DCW0101 
{
    receive_shadows on 

    technique
    {
        pass DCW0101
        {
            ambient 0.800000011920929 0.800000011920929 0.800000011920929 1.0
            diffuse 0.6400000190734865 0.6400000190734865 0.6400000190734865 1.0
            specular 0.5 0.5 0.5 1.0 12.5
            emissive 0.0 0.0 0.0 1.0

            alpha_to_coverage off
            colour_write on
            cull_hardware clockwise
            depth_check on
            depth_func less_equal
            depth_write on
            illumination_stage 
            light_clip_planes off
            light_scissor off
            lighting on
            normalise_normals off
            polygon_mode solid
            scene_blend one zero
            scene_blend_op add
            shading gouraud
            transparent_sorting on

            texture_unit 
            {
                texture DungeonWall.png
                tex_address_mode wrap
                scale 1.0 1.0
                colour_op modulate
            }
            texture_unit 
            {
                texture DungeonWallTop2.png
                tex_address_mode border
                tex_border_colour 1.0 0.0 1.0
                scale 1.0 1.0
                tex_coord_set 1
                colour_op modulate
            }
            texture_unit 
            {
                texture DungeonWallTopCrown.png
                tex_address_mode border
                tex_border_colour 1.0 0.0 1.0
                scale 1.0 1.0
                tex_coord_set 2
                colour_op modulate
            }
        }
    }
}
```

This is what i get from the blender material creator, i cant adapt to ogre can you?
i managed to do the 1 material-multi texture, but until the material is properly working i cant test, or see if the mask will get in the way at the last moment

**Comment by Bertram25** [comment] 2015-06-18 21:31
> This is what i get from the blender material creator, i cant adapt to ogre can you?
> i managed to do the 1 material-multi texture, but until the material is properly working i cant test, or see if the mask will get in the way at the last moment

Ogre will indeed search for one specific material section. (It doesn't even care about the filename, btw).
IMHO, you will have to cope with this. I mean make tests until you have a model working with a material using several textures not higher than 512x512. IMO, it is the best for us in term of performance and resources management.
Is it ok for you to keep doing that way?

**Comment by Danimal696** [comment] 2015-06-18 23:46
im fine with that, but how could i translate what i posted before to the material we are using for claimed wall?

**Comment by Bertram25** [comment] 2015-06-19 08:36
> im fine with that, but how could i translate what i posted before to the material we are using for claimed wall?

Let's try to put it all from the start as it will help me, too. From what I understand, the `RTSS_NormalMapping_Multipass` technique has three default passes. `ambient`, `lighting`, and `decal` done in this order.
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/RTShaderLib/materials/RTShaderSystem.material#L67
`lighting` permits to set the normal texture(s) in the `rtshader_system`
and `decal` permits to set the diffuse texture in the same section.

In the current Claimedwall material, you can see only the `lighting` and `decal` passes have been overriden for the ClaimedWall and that a pass named `last` has been added after the two other passes. (The `ambient` pass is still there but without change AFAIK).
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Claimedwall.material

Now if I understand your need enough, I guess you'll want to:
- Add a pass before the `lighting` one where you can add your several `texture_unit` sections to get a standard multi-texture pass.
- As for the normal mapping, I guess you'll want to have several textures, too?
  I found this but I must say I don't know whether it can work:

``` lua
pass lighting
{
    rtshader_system
    {
       lighting_stage normal_map object_space
       {
          texture_unit
          {
             texture Panels_Normal_Obj.png
             mipmap_bias -1
          }
          // Add other texture_unit here
       }
    } 
}
```

For @hwoarangmy , if you add another techique section after the first one, you can add a `lod_values`, `lod_strategy` to the second one. Could be useful to use smaller textures for farther models in the minimap.

**Comment by Danimal696** [comment] 2015-06-19 11:52
i cant put it to work for my life...
Since you gyus are the pro at materials please take a look at forum, ill be leaving a full sample of multitexturing there.

**Comment by Bertram25** [comment] 2015-07-03 20:42
Hey, :)
Multitexturing problems apart, isn't this issue fixed?

**Comment by hwoarangmy** [comment] 2015-07-03 21:01
> Multitexturing problems apart, isn't this issue fixed?

I guess so. But I will let @Danimal696 have the last word ^^

**Comment by Bertram25** [comment] 2015-07-03 21:08
Arf, yes, he's still the boss (or at least he must think so... ;})

**Comment by Danimal696** [comment] 2015-07-03 21:13
so thats what you talk behind my back? 10 whips for each of you, im fine with closing this, mutitexture material requires a lot of time to set up; so please close this issue

**Comment by Bertram25** [comment] 2015-07-03 21:22
Ok boss. ;)

**Comment by Bertram25** [comment] 2015-07-03 21:22
1 (arg), 2 (aaaaarg), 3 ...

**Closed as completed by Bertram25** 2015-07-03 21:22 UTC
Labels: Enhancement

**Comment by Bertram25** [comment] 2015-07-03 21:23
9 (owww), 10 (ahhhh), 11 (huh??!), 12 ...

**Comment by Danimal696** [comment] 2015-07-03 22:44
admit you like it...
