### ISSUE TITLE
Editor: Crash when opening, saving and closing a level without any change

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#217] opened 2014-10-03 13:56 UTC
Might be linked to line endings according to @hwoarangmy 

See here for the level tested with the windows build:
http://forum.freegamedev.net/viewtopic.php?p=59984#p59984

**Comment by hwoarangmy** [comment] 2014-10-06 09:05
I've looked at the file and it has been modified by the editor. I've seen 2 things :
- Lot of spaces have been added at each line
- subgoals handling "+ 1" have been changed to "1" resulting in every goal being considered main goals.

The problem @Danimal696 raised is caused by the spaces. Because of them, we do not see the end of the map information and we stay in an infinite loop. To fix that, I will add a trim to the parameters read from the map and check for the EOF in the loop.

**Comment by Danimal696** [comment] 2014-10-06 09:37
For more information, i used microsoft excel 2010 to modify it; i have been using it previously on the all the other releases, this is the first one to present errors with it.

**Comment by Bertram25** [comment] 2014-10-06 09:49
My proposal: @Danimal696 Never ever use an office tool to edit OD files again. I'd propose Scite and such to do so. Sorry.

**Comment by Danimal696** [comment] 2014-10-06 17:42
is there any other option closer to what excel shows? plain text editor make it very hard to see columns

**Comment by Bertram25** [comment] 2014-10-06 21:04
After the change on creatures, there won't be columns anymore in creature definitions.
Other than that, you can also set a monospaced font for your text, which should help a lot already. (That's what I do. ;])

**Comment by Bertram25** [comment] 2014-10-07 08:25
Since the level was changed using an external unsupported tool, I'd propose to close this one as won't fix.

**Comment by hwoarangmy** [comment] 2014-10-07 08:36
Even if it was modified with an unsupported tool, I think it is not acceptable to have endless loops. We might also have corrupted files or whatever. I will add in my next PR a fix to stop map loading when after EOF (at least for the case @Danimal696 raised. Concerning the subgoals handling problem, I agree, we don't have to fix it.
So I propose to close this issue when the EOF will be fixed.

**Comment by Bertram25** [comment] 2014-10-07 08:42
> So I propose to close this issue when the EOF will be fixed.

Fair enough. :)

**Closed as completed** 2014-10-09 22:30 UTC
Labels: Bug, Windows, Map Editor
