### ISSUE TITLE
Tought bubble stuck in center of my screen

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1146] opened 2016-03-28 22:26 UTC
I was playing the game, in the process of highlighting gold when suddenly a thought bubble appeared on my screen. There was no creature in sight. I moved my camera but the thought bubble was stuck.

I proceeded to make the screenshot and secured the log file:
[Ogre.zip](https://github.com/OpenDungeons/OpenDungeons/files/192568/Ogre.zip)

![hungry](https://cloud.githubusercontent.com/assets/13840686/14092054/636c4164-f544-11e5-8644-1df4a0227e3f.jpg)

**Comment by Loobinex** [comment] 2016-03-28 22:42
Pressing V made it disappear. When I got new bubbles a few minutes later I pressed 'Alt' and noticed this:

![nowwhat](https://cloud.githubusercontent.com/assets/13840686/14092384/bd541416-f546-11e5-9768-11fe7cf459cb.jpg)

All the creature icons are displayed on random dirt, way north of my dungeon, which I can toggle with Alt.

**Comment by hwoarangmy** [comment] 2016-03-29 19:05
Strange. Did you find a way to reproduce that ? Overlays are not very verbose and the logs won't say much. Did something unusual happened before the issue ?

**Comment by Loobinex** [comment] 2016-03-29 19:27
I have not tried yet, it was the last game I played and it happened over an hour in. Both times it happened I noticed nothing special and received no notifications, I was just highlighting spaces for digging when suddenly they appeared.
If I come across it again I'll let you know and I'll try to find more information. I'll also save the game to see if persists on loading.

**Comment by hwoarangmy** [comment] 2016-03-29 21:19
ok, thanks. For my part, I will have a look at the code. It might come from something not beeing reset when the creatures owning the overlays are not visible anymore

**Comment by Bertram25** [comment] 2016-03-30 21:13
I confirm the bug.

**Comment by Bertram25** [comment] 2016-03-30 21:16
@hwoarangmy Just to make sure, will you have a look for 0.7?

**Comment by hwoarangmy** [comment] 2016-03-30 21:56
Yes, I will have a look. However, I'm only going to look in the code since I don't know how to reproduce the bug so I'm not sure it will be fixed.

**Closed as completed** 2016-04-12 07:52 UTC
Labels: Bug
