### ISSUE TITLE
Game does not show up after validating the Ogre rendering settings

### ISSUE THREAD

**Issue by ghost** [OpenDungeons/OpenDungeons#781] opened 2015-05-28 09:13 UTC
Hi there,

I just tried to run OpenDungeons on my 11" notebook with Linux Mint (Ubuntu). The display resolution would be 1024x600 and lower (also tried 640_480 and 800_600 in full screen and windowed).
The only thing that is appearing is the selection for the renderer, nothing else.
I couldn't find a log file and also no information on which system the game should run. On Windows it worked fine.

Regards

G

**Comment by akien-mga** [comment] 2015-05-28 10:03
I'm not sure what the issue is exactly.
Did you select a renderer, or have you none proposed?

**Comment by hwoarangmy** [comment] 2015-05-28 20:01
I would guess at an exception while reading config files or something like that.

Could you please post your log file ?
It should be somewhere like "~/.local/share/opendungeons/opendungeons.log"

**Comment by ghost** [comment] 2015-05-29 14:12
Hi,
I think I forgot to mention I'm a Windows user. Simple commands like "copy" are unknown to this stupid Linux. It's really not nice to say "look into a folder where you can't get with the gui". 
I think it would have been too easy to drop the log file in the same directory as the game?!

And I'm also too stupid for Github. A long time ago there had been "TinyMCE" with a "<code>" button. So here's the log file without syntax highlighting.

```
10:10:17: Creating resource group General
10:10:17: Creating resource group Internal
10:10:17: Creating resource group Autodetect
10:10:17: SceneManagerFactory for type 'DefaultSceneManager' registered.
10:10:17: Registering ResourceManager for type Material
10:10:17: Registering ResourceManager for type Mesh
10:10:17: Registering ResourceManager for type Skeleton
10:10:17: MovableObjectFactory for type 'ParticleSystem' registered.
10:10:17: ArchiveFactory for archive type FileSystem registered.
10:10:17: ArchiveFactory for archive type Zip registered.
10:10:17: ArchiveFactory for archive type EmbeddedZip registered.
10:10:17: DDS codec registering
10:10:17: FreeImage version: 3.15.3
10:10:17: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
10:10:17: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,cut,xbm,xpm,gif,hdr,g3,sgi,exr,j2k,j2c,jp2,pfm,pct,pict,pic,3fr,arw,bay,bmq,cap,cine,cr2,crw,cs1,dc2,dcr,drf,dsc,dng,erf,fff,ia,iiq,k25,kc2,kdc,mdc,mef,mos,mrw,nef,nrw,orf,pef,ptx,pxn,qtk,raf,raw,rdc,rw2,rwl,rwz,sr2,srf,srw,sti
10:10:17: Registering ResourceManager for type HighLevelGpuProgram
10:10:17: Registering ResourceManager for type Compositor
10:10:17: MovableObjectFactory for type 'Entity' registered.
10:10:17: MovableObjectFactory for type 'Light' registered.
10:10:17: MovableObjectFactory for type 'BillboardSet' registered.
10:10:17: MovableObjectFactory for type 'ManualObject' registered.
10:10:17: MovableObjectFactory for type 'BillboardChain' registered.
10:10:17: MovableObjectFactory for type 'RibbonTrail' registered.
10:10:17: Loading library lib/RenderSystem_GL
10:10:17: Installing plugin: GL RenderSystem
10:10:17: OpenGL Rendering Subsystem created.
10:10:17: Plugin successfully installed
10:10:17: Loading library lib/Plugin_OctreeSceneManager
10:10:17: Installing plugin: Octree Scene Manager
10:10:17: Plugin successfully installed
10:10:17: *-*-* OGRE Initialising
10:10:17: *-*-* Version 1.9.0 (Ghadamon)
10:10:17: Load creature definition file: ./config/creatures.cfg
10:10:17: Load weapon definition file: ./config/equipments.cfg
10:10:17: Load creature spawn conditions file: ./config/spawnconditions.cfg
10:10:17: Load factions file: ./config/factions.cfg
10:10:17: Load Rooms file: ./config/rooms.cfg
10:10:17: Load traps file: ./config/traps.cfg
10:10:17: Load Spell config file: ./config/spells.cfg
10:10:17: Load creature spawn conditions file: ./config/creaturesmood.cfg
10:10:17: Load Researches file: ./config/researches.cfg
10:10:17: Load Tilesets file: ./config/tilesets.cfg
10:10:30: OverlayElementFactory for type Panel registered.
10:10:30: OverlayElementFactory for type BorderPanel registered.
10:10:30: OverlayElementFactory for type TextArea registered.
10:10:30: Registering ResourceManager for type Font
10:10:30: CPU Identifier & Features
10:10:30: -------------------------
10:10:30:  *   CPU ID: GenuineIntel: Intel(R) Atom(TM) CPU N270   @ 1.60GHz
10:10:30:  *      SSE: yes
10:10:30:  *     SSE2: yes
10:10:30:  *     SSE3: yes
10:10:30:  *      MMX: yes
10:10:30:  *   MMXEXT: yes
10:10:30:  *    3DNOW: no
10:10:30:  * 3DNOWEXT: no
10:10:30:  *     CMOV: yes
10:10:30:  *      TSC: yes
10:10:30:  *      FPU: yes
10:10:30:  *      PRO: yes
10:10:30:  *       HT: no
10:10:30: -------------------------
10:10:30: ******************************
*** Starting GLX Subsystem ***
******************************
10:10:30: Registering ResourceManager for type Texture
10:10:30: GLRenderSystem::_createRenderWindow "OpenDungeons 0.5.0", 1024x600 windowed  miscParams: FSAA=0 displayFrequency=60 Hz gamma=No vsync=No 
10:10:30: GLXWindow::create used FBConfigID = 98
10:10:30: GL_VERSION = 1.4 Mesa 10.1.3
10:10:30: GL_VENDOR = Intel Open Source Technology Center
10:10:30: GL_RENDERER = Mesa DRI Intel(R) 945GME x86/MMX/SSE2
10:10:30: GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_multitexture GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_ARB_half_float_pixel GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_pixel_buffer_object GL_ARB_texture_rectangle GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_gpu_program_parameters GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_map_buffer_range GL_EXT_separate_shader_objects GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_EXT_provoking_vertex GL_ARB_get_program_binary GL_ARB_robustness GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_invalidate_subdata GL_ARB_vertex_attrib_binding GL_KHR_debug 
10:10:30: Supported GLX extensions: GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_EXT_framebuffer_sRGB GLX_EXT_create_context_es2_profile GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_EXT_texture_from_pixmap GLX_INTEL_swap_event 
10:10:30: ***************************
10:10:30: *** GL Renderer Started ***
10:10:30: ***************************
```

I don't think there are any system recommendations anywhere for OpenDungeons + it is simply not designed for Linux Mint on a 6 year old netbook. So you can just close the ticket. And please add the minimum system to the homepage.

Regards

G

**Comment by akien-mga** [comment] 2015-05-29 19:43
I still don't understand your issue, apart from the fact that Linux seems to bother you.

The log does not show any error, actually it just shows that you started OpenDungeons... and then nothing more happens. So could you please answer my earlier question:

>  Did you select a renderer, or have you none proposed?

As for:

>  I think it would have been too easy to drop the log file in the same directory as the game?!

It's normal practice on any operating system that user-specific data should go to a standard folder, which is C:/Users/YourName/AppData on Windows and ~/.local/share on Linux. We can't just write anything in the game folder, since the game's data folder might be read-only (e.g. if you install the game system-wide on Linux).

> And please add the minimum system to the homepage.

I still fail to see what "minimum system" means here, since your log does not show any bug, so I guess you just forgot to select a renderer.

**Comment by ghost** [comment] 2015-05-29 19:56
Of course I chose a renderer, it seems I will never understand Linux, but I'm not too stupid to press a button -.-

And for this "AppData" folder: It didn't exist on Win95 where I started. So everything went into the program's or game's folder. Now I can't decide which OS to run. For university I need something newer. The something newer doesn't let me do what I want the way I want it: Very neatly, everything where it belongs, instead of spreading through the whole system without any control. So I'm running Linux, Windows 7, 8, XP, 98, 95 - whatever I want the moment I need it. If I had a choice, I would go to the Island Robinson Crusoe landed on -.-

And for your last accusement: I DID CHOOSE A RENDERER! I can't speak in 100110, therefor can't manipulate your life, but hell, I can click a stupid button!

And the log file says the same I told in the beginning: I started the game, but nothing else happened. On Windows I would have started the task manager. Only Geeks know how to start it on Linux. So I don't know what happend the next 10 minutes, until I have shut down the netbook.

And as I already said: You don't want anyone to have minimum system requirements before their eyes, so be it. Just close this here up and be done!
Now I'm very tired of speaking English. Maybe it is so bad nobody can understand me, I don't know.

**Comment by akien-mga** [comment] 2015-05-29 20:13
> Of course I chose a renderer, it seems I will never understand Linux, but I'm not too stupid to press a button -.-

You are asking for support and give very little information, it's only legitimate that I ask for more info. And yes, some people do not understand how to select a renderer, because it's not 100% clear that the empty field can be clicked to show a drop-down list. So excuse me for presuming that might be your case, but the information you gave was very sparse.

> And the log file says the same I told in the beginning: I started the game, but nothing else happened. [...] So I don't know what happend the next 10 minutes, until I have shut down the netbook.

Now that's already more useful to see what might be going wrong. So judging by the log, you are using the OpenGL renderer, and your hardware supports OpenGL 1.4, so it should work fine. There is also no error in the log. It just says that it starts the OpenGL renderer, and then it's quiet.

Normally it should go on with:

```
22:09:38: Registering ResourceManager for type GpuProgram
22:09:38: GLSL support detected
22:09:38: GL: Using GL_EXT_framebuffer_object for rendering to textures (best)
```

So maybe there's something wrong in our code for GLSL support detection.
@oyvindln, @hwoarangmy, @Bertram25, any idea?

**Comment by akien-mga** [comment] 2015-05-29 20:16
Also, if I understand correctly, OpenDungeons works on Windows on the same notebook?

**Comment by akien-mga** [comment] 2015-05-29 20:24
Another thing, could you indicate which version of OpenDungeons you are running, and where you took it from? Is it our official Linux binary for OpenDungeons 0.5.0, a third-party package from the PlayDeb repo, or did you build it from source?

**Comment by hwoarangmy** [comment] 2015-05-29 21:25
> And for your last accusement: I DID CHOOSE A RENDERER!

There is no accusement, you said Ogre windows opens and nothing happens. It's legitimate to ask if you choose something. Moreover, the bug might be that the renderer is not found for whatever reason.

> I think it would have been too easy to drop the log file in the same directory as the game?!

It would have been easy but OS with real rights handling might not allow to write everything anywhere. That's why we choose the user application folder (like most games do). Sorry for not focusing on windows only.

> And the log file says the same I told in the beginning: I started the game, but nothing else happened

AFAIK, the last log you have appears during ogre initialisation (as well as the other logs that should follow). So that's probably where there is a problem. However, I have no clue of what is going wrong.

> And as I already said: You don't want anyone to have minimum system requirements before their eyes, so be it.

That's not that we don't want minimum requirements, it is just that we don't know. You have to understand that you are talking to a small team that work on the game during their free time. We don't have the needed ressources to test on several computers (with different OS) if the game works or not.

But as @akien-mga stated, the first thing to tell is what release are you using and where it came from ?

**Comment by Bertram25** [comment] 2015-06-01 07:53
Hi there, :)

@akien-mga @hwoarangmy 
The user has been deleted for seemingly being a troll. Let's close this issue and forget about this moron.

**Closed as completed by Bertram25** 2015-06-01 07:53 UTC
Labels: Invalid
