### ISSUE TITLE
Skull flags improvement - State display part.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#734] opened 2015-05-05 17:07 UTC
See also #733 

As discussed in:
http://forum.freegamedev.net/viewtopic.php?f=35&t=6299

Skull flags should also display when:
- A creature is in bad mood.
- A creature wants to quit the dungeon.
- A creature has become feral.
- A creature is sleepy.
- A creature is hungry.
- A Creature is on its way to get its pay.
- A creature is KO (for the arena)

Small icons shown above the skull flags have been proposed as an implementation.
Icons for each must be found and added as a first step.

**Comment by hwoarangmy** [comment] 2015-05-05 19:07
Note that it doesn't have to be the skull flag (but another overlay)

**Comment by Bertram25** [comment] 2015-05-05 22:10
True :)

**Comment by Danimal696** [comment] 2015-05-06 12:30
Creature is on its way to get its pay
Creature is hungry

i would propose the skull flags changes to this new icons, and they are always visible so you can easily locate affected creature, except when hovering them or pressing Alt or in battle that the skull flag will reappear

**Comment by Bertram25** [comment] 2015-05-06 13:56
@Danimal696 

> i would propose the skull flags changes to this new icons, and they are always visible so you can easily locate affected creature, except when hovering them or pressing Alt or in battle that the skull flag will reappear

@hwoarangmy will know more, but AFAIK changing the skull flag texture itself would force us to create 8 health states per icons and it's not relevant in term of development effort.

**Comment by akien-mga** [comment] 2015-05-06 14:40
> AFAIK changing the skull flag texture itself would force us to create 8 health states per icons and it's not relevant in term of development effort

IIUC @Danimal696 meant not to display the skull flag, but display a status flag instead. Personally I think we should keep the skull flag, and just add a second overlay on top of it, like a small coloured icon at the bottom right of the skull flag.

**Comment by Bertram25** [comment] 2015-05-06 14:48
> IIUC @Danimal696 meant not to display the skull flag, but display a status flag instead.

Indeed. :) But as we'll still want to know about the creature health level, it will mean 8 state per icon.

> Personally I think we should keep the skull flag, and just add a second overlay on top of it, like a small coloured icon at the bottom right of the skull flag.

I do also think alike. Let's see whether the others have something to add here.

**Comment by hwoarangmy** [comment] 2015-05-06 19:54
> AFAIK changing the skull flag texture itself would force us to create 8 health states per icons and it's not relevant in term of development effort.

Yes. So far, it is not possible to dynamically change the skull flag. Moreover, It is IMHO too big to be displayed automatically. To display some creature state, another overlay should be better IMO.

**Comment by Bertram25** [comment] 2015-05-07 10:58
> To display some creature state, another overlay should be better IMO.

I guess it's settled then. :) Sorry @Danimal696 but I'm sure we'll find something good looking using another overlay.

**Comment by Danimal696** [comment] 2015-05-07 11:04
ohhhhhh, you are breaking my lil evil heart :p
no prob here

**Comment by Bertram25** [comment] 2015-05-07 11:09
Icons proposal:
- A creature is in bad mood: http://game-icons.net/lorc/originals/death-zone.html http://game-icons.net/lorc/originals/lizardman.html
- A creature wants to quit the dungeon: http://game-icons.net/lorc/originals/spade-skull.html
- A creature has become feral: http://game-icons.net/lorc/originals/pirate-skull.html
- A creature is sleepy: http://game-icons.net/lorc/originals/sleepy.html (We could also reuse the dormitory room icon.)
- A creature is hungry: http://game-icons.net/lorc/originals/carrion.html
- A creature is on its way to get its pay: http://game-icons.net/lorc/originals/cool-spices.html http://game-icons.net/lorc/originals/crown-coin.html http://game-icons.net/lorc/originals/snatch.html
- A creature is KO: http://game-icons.net/lorc/originals/smitten.html (I'd replace the hearts in his eyes with crosses.)

**Comment by Danimal696** [comment] 2015-05-07 11:53
Bad mood, i like lizarman better; the hand and bag for payday
for KO: http://game-icons.net/lorc/originals/pummeled.html
for quitting:
http://game-icons.net/lorc/originals/journey.html
http://game-icons.net/lorc/originals/pig-face.html

Hey, this could be good for workshop: http://game-icons.net/lorc/originals/gear-hammer.html

**Comment by hwoarangmy** [comment] 2015-05-07 12:22
Bad mood (angry): http://game-icons.net/lorc/originals/pummeled.html
Bad mood (furious): http://game-icons.net/lorc/originals/spade-skull.html
Leaving: http://game-icons.net/lorc/originals/journey.html
Become feral: No need for an icon
sleepy: Good
Hungry: ok if nothing else
Get paid: http://game-icons.net/lorc/originals/snatch.html
KO: I prefer @Bertram25 's one.

**Comment by Bertram25** [comment] 2015-05-07 13:32
> Hey, this could be good for workshop: http://game-icons.net/lorc/originals/gear-hammer.html

I must say I prefer the current one. But if everyone prefer this one, I won't mind adding it.

**Comment by Bertram25** [comment] 2015-05-07 13:34
> Become feral: No need for an icon

Why? Because, for instance, red fighting red makes it obvious? Or is there a technical reason?

**Comment by akien-mga** [comment] 2015-05-07 13:41
> > Become feral: No need for an icon
> 
> Why? Because, for instance, red fighting red makes it obvious? Or is there a technical reason?

I guess units becoming feral would change their factions, no?

**Comment by hwoarangmy** [comment] 2015-05-07 13:41
> Because, for instance, red fighting red makes it obvious?

Because IMHO, it is a bug that when a creature becomes feral, the skull flag is not replaced. And the technical reason is that I don't think it is a good thing to make a difference between feral from start and feral because of mood. Especially things that are player specific (since other players should not see any difference I guess).

**Comment by Bertram25** [comment] 2015-05-07 13:44
Makes sense.

**Comment by Danimal696** [comment] 2015-05-07 14:45
not to me? i think a creature going rogue or feral has switched to the feral team present on map, so if their skull changes to white (if thats the colour used for unaligned creatures on that map) and i get some voice message about what just happened, i understand quite well that creature its not mine anymore, not to confuse with angry creatures hitting others(like spiders/flies).

Having a feral of my colour will make me wonder why i cant pick it up, that wont happen if it changes colour

**Comment by Bertram25** [comment] 2015-05-07 14:58
> not to me?

@Danimal696 In fact, I do think @hwoarangmy and you are thinking the sameas he said he considers that the skull flag not being updated is a bug.

If you guys are ok with it, I'll open an issue about it.

**Comment by hwoarangmy** [comment] 2015-05-07 16:36
To be honest, I've only seen that in @eugeneloza replay (where he was complaining that heroes were fighting each others) but I had not seen by myself.
I wanted to check but I didn't take time yet. However, if it is confirmed, it is definitely a bug and should be fixed. So please feel free to open the issue if you confirm the bug.

**Comment by Bertram25** [comment] 2015-05-08 06:12
Ok, I've also witnessed that but I will try with latest change to make sure before opening the issue. :)

**Comment by Bertram25** [comment] 2015-05-08 07:11
I confirm the issue. Creatures that cannot leave the dungeon and become feral are keeping their former color.

**Comment by Danimal696** [comment] 2015-05-08 09:42
i comfirm too, after a very nice spider-fly experiment

**Comment by Bertram25** [comment] 2015-05-13 21:17
![ko](https://cloud.githubusercontent.com/assets/765917/7621322/42a098d8-f9c6-11e4-9dbb-443287035e8f.png)
For later reference.

**Closed as completed** 2015-05-15 22:28 UTC
Labels: Enhancement, Game content
