### ISSUE TITLE
Exiting with window button does not clean up sockets properly

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#600] opened 2015-03-30 13:28 UTC
If I exit the game and start it again right away a new game can't be started as the port is in use (On my system (Ubuntu 14.10) at least). I don't know if there is an issue of ports not being closed, or if the OS reserves the port for a while after the application is done. This is frustrating when working with materials or other things where the game has to be restarted to test the effects.

If it is not a bug, a single player game should try a different port if the first one fails when starting.

**Comment by hwoarangmy** [comment] 2015-03-30 13:45
We close the socket listener in ODSocketServer::stopServer. AFAIK, it is enough to gracefully close the socket.
I don't know why you get this error. As you suggest, a workaround would be to use a different socket if we fail opening the required one. But I'm not sure it is such a good idea to open sockets on ports we are not supposed to use. A better solution may be to add some sleep when opening the socket when it fails before re-trying. But it will be slower to open the game for your tests.

**Comment by oyvindln** [comment] 2015-03-30 13:51
Adding a sleep doesn't really solve the issue, it takes way to long before I can restart in the first place.

**Comment by hwoarangmy** [comment] 2015-03-30 14:03
I found something interesting. The issue is in SFML.
http://en.sfml-dev.org/forums/index.php?topic=11545.0

It seems like SFML do not close the socket as it should. Moreover, it doesn't give access to the shutdown function that would allow to close the socket as we should.I don't know if it is fixed in newer versions of SFML but in the issue (link is in the thread I pasted), it is said that the issue is still there in a message posted on August 2014. So, it is probably still true.

**Comment by oyvindln** [comment] 2015-03-30 14:19
I'm a bit unsure if it's the same problem, it works fine to exit to the main menu and start a new game right away. It's only when restarting the application it won't work.

**Comment by hwoarangmy** [comment] 2015-03-30 15:31
Well, I don't really know as I don't reproduce the bug but if you can launch 2 games in a row, I agree that the socket is closed and re-launched in the process. If it is the case, you are right, it might be another problem. How do you restart the game ? Do you kill the application (I guess not but I prefer to ask) ?

**Comment by oyvindln** [comment] 2015-03-30 15:33
I close it normally, either with the x window button or with the exit button in the menu.

**Comment by akien-mga** [comment] 2015-03-30 15:38
I can reproduce the issue, if I close OD while in game using the X window button, and restart OD afterwards, I can't start a new server.

If I quit OD using the quit menu (i.e. quit to main menu, then quit to OS), I don't reproduce the bug, I can start a new game in a new OD instance.

**Comment by Bertram25** [comment] 2015-03-30 15:45
Exact same for me than for @akien-mga . The issue is there since a lot of time IIRC.

**Comment by oyvindln** [comment] 2015-03-30 16:16
That seems to be the case here as well. For some reason I never noticed that.

**Comment by hwoarangmy** [comment] 2015-03-30 16:17
Strange, I've never seen that and I've already tried to close/launch OD many times. I will give it a try but I think I would have already seen that if it was reproducible with windows. That may also be a different event handling between windows/linux when we close by pressing the X button. Maybe in this case, the server is not stopped (and I confirm it is on windows as I've already seen that the gamemap is cleaned which happens when the server is closed).

**Comment by hwoarangmy** [comment] 2015-03-30 18:39
I confirm I do not have the bug with windows. I guess it means that the socket is not proporly closed when you clic the exit button (to test that, could you please add a log in ODServer::stopServer) or the socket automatic close is shorter on windows. I would guess at first possibility because otherwise, there is no reason that you could launch 2 games in a row

**Comment by Bertram25** [comment] 2015-04-06 17:21
I'll test adding logs tonight.

**Comment by Bertram25** [comment] 2015-04-06 20:32
Exiting the application (using the cross) while playing:

```
Stopping server...
*********************** ODServer::stopServer() begin
*********************** ODSocketServer::stopServer()

Computing turn 5
During this turn there were 8 calls to GameMap::path().miscUpkeepTime=7341
*********************** ODSocketServer::stopServer() end
SERVER - Removing Creature Spider1
SERVER - Removing Creature Spider2
SERVER - Removing Creature Spider3
SERVER - Removing Creature Spider4
SERVER - Removing Creature Spider5
SERVER - Removing Creature Spider6
SERVER - Removing Creature Spider7
SERVER - Removing Creature Spider8
SERVER - Removing Creature Spider9
SERVER - Removing Creature Spider10
SERVER - Removing Creature Spider11
SERVER - Removing Creature Spider12
SERVER - Removing Creature Spider13
SERVER - Removing Creature Spider14
SERVER - Removing Creature Spider15
SERVER - Removing Creature Spider16
SERVER - Removing Creature Spider17
SERVER - Removing Creature Spider18
SERVER - Removing Creature Kobold1
SERVER - Removing Creature Slime2
SERVER - Removing Creature Spider19
SERVER - Removing Creature TentacleAlbine20
SERVER - Removing Creature Slime21
SERVER - Removing room DungeonTemple1
SERVER - Removing rendered object RenderedMovableEntity_DungeonTemple1_1,MeshName=DungeonTempleObject
SERVER - Removing room Portal2
SERVER - Removing rendered object RenderedMovableEntity_Portal2_2,MeshName=PortalObject
SERVER - Removing room Portal3
SERVER - Removing rendered object RenderedMovableEntity_Portal3_3,MeshName=PortalObject
SERVER - Removing room DungeonTemple4
SERVER - Removing rendered object RenderedMovableEntity_DungeonTemple4_4,MeshName=DungeonTempleObject
SERVER - Removing room Portal5
SERVER - Removing rendered object RenderedMovableEntity_Portal5_5,MeshName=PortalObject
SERVER - Removing room Portal6
SERVER - Removing rendered object RenderedMovableEntity_Portal6_6,MeshName=PortalObject
SERVER - Removing room Treasury1
*********************** ODServer::stopServer() end
Disconnecting client...
Render Target 'OpenDungeons 0.5.0' Average FPS: 37.2221 Best FPS: 59.5829 Worst FPS: 31.2805
Closing down.
*********************** ODServer::notifyExit()
*********************** ODSocketServer::stopServer()
*********************** ODSocketServer::stopServer() end
*********************** ODServer::notifyExit() end
CLIENT - Removing Creature Spider19
CLIENT - Removing Creature Slime2
CLIENT - Removing rendered object RenderedMovableEntity_Portal3_3,MeshName=PortalObject
CLIENT - Removing rendered object RenderedMovableEntity_Portal2_2,MeshName=PortalObject
CLIENT - Removing rendered object RenderedMovableEntity_DungeonTemple1_1,MeshName=DungeonTempleObject
Remove listener registration
Frame listener uninitialization done.
*** Destroying Input Manager ***
```

Stopping using the Escape/Yes, then Quit button:

```
*********************** ODServer::stopServer() begin
*********************** ODSocketServer::stopServer()
Client disconnected state=ready

Computing turn 2
RoomPortal name=Portal2spawns a creature class=TentacleGreen, name=TentacleGreen2, seatId=1
SERVER - Adding Creature TentacleGreen2, seatId=1
RoomPortal name=Portal3spawns a creature class=TentacleAlbine, name=TentacleAlbine3, seatId=1
SERVER - Adding Creature TentacleAlbine3, seatId=1
RoomPortal name=Portal5spawns a creature class=CaveHornet, name=CaveHornet4, seatId=2
SERVER - Adding Creature CaveHornet4, seatId=2
RoomPortal name=Portal6spawns a creature class=Spider, name=Spider19, seatId=2
SERVER - Adding Creature Spider19, seatId=2
During this turn there were 19 calls to GameMap::path().miscUpkeepTime=7140
SERVER - Adding room Treasury1, nbTiles=1, seatId=2
SERVER - Adding room Treasury1, tile=[50,23]
*********************** ODSocketServer::stopServer() end
SERVER - Removing Creature Spider1
SERVER - Removing Creature Spider2
SERVER - Removing Creature Spider3
SERVER - Removing Creature Spider4
SERVER - Removing Creature Spider5
SERVER - Removing Creature Spider6
SERVER - Removing Creature Spider7
SERVER - Removing Creature Spider8
SERVER - Removing Creature Spider9
SERVER - Removing Creature Spider10
SERVER - Removing Creature Spider11
SERVER - Removing Creature Spider12
SERVER - Removing Creature Spider13
SERVER - Removing Creature Spider14
SERVER - Removing Creature Spider15
SERVER - Removing Creature Spider16
SERVER - Removing Creature Spider17
SERVER - Removing Creature Spider18
SERVER - Removing Creature Kobold1
SERVER - Removing Creature TentacleGreen2
SERVER - Removing Creature TentacleAlbine3
SERVER - Removing Creature CaveHornet4
SERVER - Removing Creature Spider19
SERVER - Removing room DungeonTemple1
SERVER - Removing rendered object RenderedMovableEntity_DungeonTemple1_1,MeshName=DungeonTempleObject
SERVER - Removing room Portal2
SERVER - Removing rendered object RenderedMovableEntity_Portal2_2,MeshName=PortalObject
SERVER - Removing room Portal3
SERVER - Removing rendered object RenderedMovableEntity_Portal3_3,MeshName=PortalObject
SERVER - Removing room DungeonTemple4
SERVER - Removing rendered object RenderedMovableEntity_DungeonTemple4_4,MeshName=DungeonTempleObject
SERVER - Removing room Portal5
SERVER - Removing rendered object RenderedMovableEntity_Portal5_5,MeshName=PortalObject
SERVER - Removing room Portal6
SERVER - Removing rendered object RenderedMovableEntity_Portal6_6,MeshName=PortalObject
SERVER - Removing room Treasury1
*********************** ODServer::stopServer() end
Closing down.
*********************** ODServer::notifyExit()
*********************** ODSocketServer::stopServer()
*********************** ODSocketServer::stopServer() end
*********************** ODServer::notifyExit() end
Remove listener registration
Frame listener uninitialization done.
Stopping server...
*********************** ODServer::stopServer() begin
*********************** ODSocketServer::stopServer()
*********************** ODSocketServer::stopServer() end
*********************** ODServer::stopServer() end
Disconnecting client...
Render Target 'OpenDungeons 0.5.0' Average FPS: 32.6953 Best FPS: 59.5829 Worst FPS: 19.6078
```

**Comment by hwoarangmy** [comment] 2015-04-06 21:01
looks pretty similar, no ?

**Comment by Bertram25** [comment] 2015-04-06 22:35
Yes and no (even if I didn't have the time to test a lot).
Seems to me that the notifyExit() is calling ODSocketServer::stopServer() twice. But commenting the call in notifyExit() doesn't change anything.
Secondly, when exiting normally, we can see a line telling the client disconnected successfully.
I don't know yet whether it could be related. I don't know what other differences there are yet, too. :)

**Comment by hwoarangmy** [comment] 2015-04-08 08:51
@Bertram25 You are right, I had not seen the difference at the beginning of your log. Indeed, the difference might be that when we close OD with the window cross, a client is still connected while the server is closed (and as pointed in the SFML link, it seems the socket is not properly closed).

IMHO, the easiest would be to close the server after the client. That would mean to invert close order in ODApplication.cpp:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/ODApplication.cpp#L136

And replace

```
logManager.logMessage("Stopping server...");
server.stopServer();
logManager.logMessage("Disconnecting client...");
client.disconnect();
```

by

```
logManager.logMessage("Disconnecting client...");
client.disconnect();
logManager.logMessage("Stopping server...");
server.stopServer();
```

@Bertram25 @akien-mga @oyvindln Could one of you please try that ?

**Comment by Bertram25** [comment] 2015-04-08 08:54
I'll do asap. Thanks for the hindsight. :)

**Comment by hwoarangmy** [comment] 2015-04-08 09:00
> I'll do asap. Thanks for the hindsight. :)

Always welcome ;-) If it works, please feel free to do the PR ^^

**Closed as completed** 2015-04-09 08:43 UTC
Labels: Bug
