### ISSUE TITLE
Strange cursor remains...

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#1089] opened 2016-01-29 07:50 UTC
![160129_cursor](https://cloud.githubusercontent.com/assets/10726162/12670010/817544d6-c66d-11e5-84c5-f058ce0c372e.jpg)
Today after testing OD for a few minutes I've experienced a strange cursor (afair after a left/right/middle click on a creature). A circle appeared where I've clicked and remained in the same position in the viewport.

**Comment by akien-mga** [comment] 2016-01-29 08:13
Yep, that's the Mysterious CEGUI Artefact(tm) ;)

Duplicate of #752.

**Closed as completed by akien-mga** 2016-01-29 08:13 UTC
Labels: Duplicate
