### ISSUE TITLE
Server segfault when client choose a different map from the server's

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#67] opened 2014-08-13 17:59 UTC
This is expected, but I report it nonetheless: if you create a server with map A, and a client connects and chose map B, the server segfaults (the client doesn't, and just says that the server disconnected).

```
Connected to server successfully
New client connected
New client accepted
Added player: LeBoss
Added player: Keeper AI 1
Player=LeBoss has been accepted in the game on color=1
Added player: Keeper AI 2
New client connected
New client accepted
Server rejected client awaited map= ./levels/multiplayer/TestMultiplayer.level, received=./levels/multiplayer/TestMultiplayerSmall.level
signal 11 (Segmentation fault), address is 0x18 from 0x7fcfb888dc78

[bt]: (1) /lib64/libstdc++.so.6 : std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)+0x8 [0x7fcfb888dc78]
[bt]: (2) /lib64/libstdc++.so.6 : std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)+0x8 [0x7fcfb888dc78]
[bt]: (3) ./OpenDungeons.bin : ODServer::notifyClientMessage(ODSocketClient*)+0x68 [0x5dadf8]
[bt]: (4) ./OpenDungeons.bin : ODSocketServer::doTask(int)+0xfc [0x5ddccc]
[bt]: (5) ./OpenDungeons.bin : ODServer::serverThread()+0x42 [0x5dca82]
[bt]: (6) /lib64/libsfml-system.so.2 : +0x73b8 [0x7fcfb8f183b8]
[bt]: (7) /lib64/libpthread.so.0 : +0x65ed [0x7fcfb8ade5ed]
[bt]: (8) /lib64/libc.so.6 : clone+0x6d [0x7fcfb7feae5d]
```

Maybe we should test for concordance between server map and client map before trying to use it?

Another question, but I don't think we should cater for it now: the maps seem to be characterised by their relative path for now, so what would happen if player renamed one of the maps or a custom made map as an existing one? Would it segfault, or would the server and the client play different maps but still try to communicate?

**Comment by hwoarangmy** [comment] 2014-08-13 19:26
Segfault is not the expected behaviour when the map is different ;)
In fact, it should just disconnect the client and keep waiting. I'm gonna see if I can reproduce.

**Comment by Bertram25** [comment] 2014-08-13 19:39
Note that by design, the client shoudn't have to select a map. The server should tell it what map to load and reject it whenever it doesn't have it.

**Comment by Bertram25** [comment] 2014-08-13 19:50
> Added player: LeBoss

XD

**Comment by hwoarangmy** [comment] 2014-08-13 20:48
That's a good idea. I'm gonna make an issue for this

**Comment by akien-mga** [comment] 2014-08-18 20:13
For the reference, issue #70 would obsolete this bug. But this one is still relevant since issue #70 is aimed at a later milestone, while we would like this one fixed for the 0.4.9 release.

**Comment by Bertram25** [comment] 2014-08-18 20:37
True. Nice catch. Issue #70 should be set back to 0.4.9 and supersedes this one. I'll do it.

**Comment by Bertram25** [comment] 2014-08-18 20:38
Supersedes by #70. Closing.

**Closed as completed by Bertram25** 2014-08-18 20:38 UTC
Labels: Bug
