### ISSUE TITLE
Heal a healthy creature

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#723] opened 2015-05-03 11:41 UTC
I can heal a healthy creature with a healing spell. It doesn't seem to eat up the mana, but triggeres a cooldown (latest dev snapshot of 3.05).

**Comment by eugeneloza** [comment] 2015-05-03 11:53
Hmmm... the spell actually appears to do nothing (the creature is killed almost a few moments after it was healed) and doesn't use mana (as it was 250 000 it remained so)

**Comment by akien-mga** [comment] 2015-05-03 17:05
> Hmmm... the spell actually appears to do nothing (the creature is killed almost a few moments after it was healed) and doesn't use mana (as it was 250 000 it remained so)

Yeah, only the cooldown will be triggered. We decided to do that at first, but after testing it we think it would be better to do nothing, cf. #710.

**Comment by akien-mga** [comment] 2015-05-03 17:05
Closing as duplicate of #710.

**Closed as completed by akien-mga** 2015-05-03 17:05 UTC
Labels: Duplicate
